In [89]:
import requests, json
import pandas as pd
import numpy as np

In [ ]:
def RREO(an_exercicio, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente):
    url = f'https://apidatalake.tesouro.gov.br/ords/siconfi/tt//rreo?an_exercicio={an_exercicio}&nr_periodo={nr_periodo}&co_tipo_demonstrativo={co_tipo_demonstrativo}&no_anexo={no_anexo}&co_esfera=&id_ente={id_ente}'
    response = requests.get(url)
    if(response.status_code != 200): 
            return({result:'Falhou'})
    dados = response.json()
    return dados

In [137]:
an_exercicio = ['2019','2020','2021','2022','2024']
id_ente = "11" #Código IBGE do Ente.

rreo_df = pd.DataFrame()
co_tipo_demonstrativo = 'RREO' #tipo de demonstrativo RREO - Bimestre
nr_periodo = '6' #periodo RREO - Bimestre
no_anexo = 'RREO-Anexo 03'

for i in an_exercicio:
    dados = RREO(i, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente)
    df = dados['items']
    df = pd.DataFrame(df)
    rreo_df = pd.concat([rreo_df, df], ignore_index=True)
    rreo_df['valor_bilhoes'] = (rreo_df['valor'] / 1000000000).round(2)

In [138]:
rreo_df['coluna'] = np.where(rreo_df['coluna'].str.contains('PREVISÃO ATUALIZADA', na=False), 'PREVISÃO ATUALIZADA', rreo_df['coluna'])

In [139]:
rreo_df['coluna'].unique()

array(['<MR-11>', '<MR-10>', '<MR-9>', '<MR-8>', '<MR-7>', '<MR-6>',
       '<MR-5>', '<MR-4>', '<MR-3>', '<MR-2>', '<MR-1>', '<MR>',
       'TOTAL (ÚLTIMOS 12 MESES)', 'PREVISÃO ATUALIZADA'], dtype=object)

In [140]:
receitas_correntes_anexo_03 = [
    'Transferências Correntes',
    'Impostos, Taxas e Contribuições de Melhoria',
]

rc_03 = rreo_df[(rreo_df['conta'].isin(receitas_correntes_anexo_03))& rreo_df['coluna'].isin(['TOTAL (ÚLTIMOS 12 MESES)','PREVISÃO ATUALIZADA'])]

In [141]:
rc_03.pivot_table(index=['exercicio','conta'], columns='coluna', values='valor_bilhoes', aggfunc='sum')

coluna                                                 PREVISÃO ATUALIZADA  \
exercicio conta
2019      Impostos, Taxas e Contribuições de Melhoria                 4.84
          Transferências Correntes                                    4.13
2020      Impostos, Taxas e Contribuições de Melhoria                 4.80
          Transferências Correntes                                    5.02
2021      Impostos, Taxas e Contribuições de Melhoria                 5.61
          Transferências Correntes                                    4.84
2022      Impostos, Taxas e Contribuições de Melhoria                 7.22
          Transferências Correntes                                    5.60
2024      Impostos, Taxas e Contribuições de Melhoria                 9.52
          Transferências Correntes                                    7.68

coluna                                                 TOTAL (ÚLTIMOS 12 MESES)
exercicio conta
2019      Impostos, Taxas e Contribuições de Melhoria                      5.00
          Transferências Correntes                                         4.24
2020      Impostos, Taxas e Contribuições de Melhoria                      5.38
          Transferências Correntes                                         4.92
2021      Impostos, Taxas e Contribuições de Melhoria                      6.91
          Transferências Correntes                                         5.37
2022      Impostos, Taxas e Contribuições de Melhoria                      7.37
          Transferências Correntes                                         6.38
2024      Impostos, Taxas e Contribuições de Melhoria                      9.34
          Transferências Correntes                                         7.70

In [142]:
an_exercicio = ['2019','2020','2021','2022','2024']
id_ente = "11" #Código IBGE do Ente.

rreo_df = pd.DataFrame()
co_tipo_demonstrativo = 'RREO' #tipo de demonstrativo RREO - Bimestre
nr_periodo = '6' #periodo RREO - Bimestre
no_anexo = 'RREO-Anexo 01'

for i in an_exercicio:
    dados = RREO(i, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente)
    df = dados['items']
    df = pd.DataFrame(df)
    rreo_df = pd.concat([rreo_df, df], ignore_index=True)
    rreo_df['valor_bilhoes'] = (rreo_df['valor'] / 1000000000).round(2)

In [143]:
receitas_correntes_anexo_01 = [
    'ReceitaDeContribuicoes',
    'ReceitaPatrimonial',
    'ReceitaDeServicos',
    'OutrasReceitasCorrentes',
    'ReceitasIntraOrcamentariasTotal'
]

rc_01 = rreo_df[ (rreo_df['cod_conta'].isin(receitas_correntes_anexo_01))
                 & (rreo_df['coluna'].isin(['Até o Bimestre (c)']))]

In [144]:
rc_01.pivot_table(index=['exercicio','conta'], columns='coluna', values='valor_bilhoes', aggfunc='sum')

coluna                                         Até o Bimestre (c)
exercicio conta
2019      CONTRIBUIÇÕES                                      0.36
          OUTRAS RECEITAS CORRENTES                          0.27
          RECEITA DE SERVIÇOS                                0.28
          RECEITA PATRIMONIAL                                0.36
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.35
2020      CONTRIBUIÇÕES                                      0.36
          OUTRAS RECEITAS CORRENTES                          0.26
          RECEITA DE SERVIÇOS                                0.28
          RECEITA PATRIMONIAL                                0.40
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.43
2021      CONTRIBUIÇÕES                                      0.38
          OUTRAS RECEITAS CORRENTES                          0.31
          RECEITA DE SERVIÇOS                                0.35
          RECEITA PATRIMONIAL                                0.36
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.36
2022      CONTRIBUIÇÕES                                      0.49
          OUTRAS RECEITAS CORRENTES                          0.41
          RECEITA DE SERVIÇOS                                0.42
          RECEITA PATRIMONIAL                                0.88
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.71
2024      CONTRIBUIÇÕES                                      0.62
          OUTRAS RECEITAS CORRENTES                          0.58
          RECEITA DE SERVIÇOS                                0.49
          RECEITA PATRIMONIAL                                0.65
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                1.12

In [150]:
total_rc_01 = rc_01[(rc_01['coluna'] == 'Até o Bimestre (c)')&(rc_01['exercicio'] == 2024)]['valor_bilhoes'].sum()
total_rc_03 = rc_03[(rc_03['coluna'] == 'TOTAL (ÚLTIMOS 12 MESES)')&(rc_03['exercicio'] == 2024)]['valor_bilhoes'].sum()
print(total_rc_01)
print(total_rc_03)
total_rc = total_rc_01 + total_rc_03
print(total_rc)

3.46
17.04
20.5

In [ ]:
#Receitas correntes

receitas_correntes_anexo_01 = [
    'CONTRIBUIÇÕES',
 'RECEITA PATRIMONIAL',
 'RECEITA DE SERVIÇOS',
 'OUTRAS RECEITAS CORRENTES',
 'RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)'
]

receitas_correntes_anexo_03 = [
    'Transferências Correntes',
    'Impostos, Taxas e Contribuições de Melhoria',
]


#'OPERAÇÕES DE CRÉDITO',
#'ALIENAÇÃO DE BENS',
#'TRANSFERÊNCIAS DE CAPITAL',
#'OUTRAS RECEITAS DE CAPITAL',
#'Transferências Constitucionais e Legais',
#'Dedução de Receita para Formação do FUNDEB'





receitas_correntes = pd.concat([df_01, df_03], ignore_index=True)

receitas_correntes['valor_bilhoes'] = (receitas_correntes['valor'] / 1000000000).round(2)

receitas_correntes.pivot_table(index='conta', columns='anexo', values='valor_bilhoes', aggfunc='sum')

anexo                                RREO-Anexo 01
conta
CONTRIBUIÇÕES                                 3.54
OUTRAS RECEITAS CORRENTES                     2.40
RECEITA DE SERVIÇOS                           1.62
RECEITA PATRIMONIAL                           2.29
RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)           5.24

In [64]:
df_03

Empty DataFrame
Columns: [exercicio, demonstrativo, periodo, periodicidade, instituicao, cod_ibge, uf, populacao, anexo, esfera, rotulo, coluna, cod_conta, conta, valor, valor_bilhoes]
Index: []