In [2]:
import requests, json
import pandas as pd
import numpy as np

In [ ]:
exercicio = 2024

an_exercicio = ['2019','2020','2021','2022','2023','2024']

id_ente = "11" #Código IBGE do Ente. rondonia 11 sao paulo 35 RS 43

#RREO
no_anexo_rreo = ['RREO-Anexo 01','RREO-Anexo 03','RREO-Anexo 06','RREO-Anexo 14'] #'RREO-Anexo 13', 'RREO-Anexo 04', 'RREO-Anexo 11', 'RREO-Anexo 09', 'RREO-Anexo 02', 'RREO-Anexo 07','RREO-Anexo 14', 'RREO-Anexo 06', 'RREO-Anexo 10 - RPPS']
nr_periodo_rreo = '6' #periodo RREO - Bimestre

#RGF
no_anexo_rgf = ['RGF-Anexo 01'] #'RREO-Anexo 13', 'RREO-Anexo 04', 'RREO-Anexo 11', 'RREO-Anexo 09', 'RREO-Anexo 02', 'RREO-Anexo 07','RREO-Anexo 14', 'RREO-Anexo 06', 'RREO-Anexo 10 - RPPS']
in_periodicidade = "Q" #S = Semestral ou Q = quadrimestral.
nr_periodo_rgf = "3" #Quadrimestre ou semestre de referência do relatório dentro de um exercício.
co_poder = "E" #E = Executivo, L = Legislativo, J = Judiciário, M = Ministério Público, D = Defensoria Pública

In [6]:
def RREO(an_exercicio, nr_periodo_rreo, no_anexo_rreo, id_ente):
    url = f'https://apidatalake.tesouro.gov.br/ords/siconfi/tt//rreo?an_exercicio={an_exercicio}&nr_periodo={nr_periodo_rreo}&co_tipo_demonstrativo=RREO&no_anexo={no_anexo_rreo}&co_esfera=&id_ente={id_ente}'
    response = requests.get(url)
    dados = response.json()
    return pd.DataFrame(dados['items'])

def RGF(an_exercicio,in_periodicidade, nr_periodo_rgf, no_anexo_rgf, co_poder, id_ente):
    url = f"https://apidatalake.tesouro.gov.br/ords/siconfi/tt//rgf?an_exercicio={an_exercicio}&in_periodicidade={in_periodicidade}&nr_periodo={nr_periodo_rgf}&co_tipo_demonstrativo=RGF&no_anexo={no_anexo_rgf}&co_esfera=&co_poder={co_poder}&id_ente={id_ente}"
    response = requests.get(url)
    dados = response.json()
    return pd.DataFrame(dados['items'])

In [8]:
rreo_df = pd.DataFrame()

for i in an_exercicio:
    for j in no_anexo_rreo:
        df = RREO(i, nr_periodo_rreo, j, id_ente)
        rreo_df = pd.concat([rreo_df, df])

In [9]:
rreo_df

,exercicio,demonstrativo,periodo,periodicidade,instituicao,cod_ibge,uf,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor
0,2019,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11329605,RREO-Anexo 01,E,Padrão,PREVISÃO INICIAL,ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),5.784073e+10
1,2019,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11329605,RREO-Anexo 01,E,Padrão,PREVISÃO ATUALIZADA (a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),5.784073e+10
2,2019,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11329605,RREO-Anexo 01,E,Padrão,No Bimestre (b),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.163289e+10
3,2019,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11329605,RREO-Anexo 01,E,Padrão,% (b/a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),2.011000e+01
4,2019,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11329605,RREO-Anexo 01,E,Padrão,Até o Bimestre (c),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),5.504996e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2024,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11088065,RREO-Anexo 14,E,Padrão,Valor Apurado no Exercício,AplicacaoDosRecursosDaAlienacaoDeAtivosDemonst...,Aplicação dos Recursos da Alienação de Ativos,1.736555e+09
120,2024,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11088065,RREO-Anexo 14,E,Padrão,Saldo a Realizar,AplicacaoDosRecursosDaAlienacaoDeAtivosDemonst...,Aplicação dos Recursos da Alienação de Ativos,7.330697e+08
121,2024,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11088065,RREO-Anexo 14,E,Padrão,Valor Apurado Até o Bimestre,AplicacaoTotalDasDespesasComAcoesEServicosPubl...,Despesas com Ações e Serviços Públicos de Saúd...,6.189875e+09
122,2024,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11088065,RREO-Anexo 14,E,Padrão,% Mínimo a Aplicar no Exercício,AplicacaoTotalDasDespesasComAcoesEServicosPubl...,Despesas com Ações e Serviços Públicos de Saúd...,1.200000e+01
123,2024,RREO,6,B,Governo do Estado do Rio Grande do Sul,43,RS,11088065,RREO-Anexo 14,E,Padrão,% Aplicado Até o Bimestre,AplicacaoTotalDasDespesasComAcoesEServicosPubl...,Despesas com Ações e Serviços Públicos de Saúd...,1.215000e+01

In [10]:
rgf_df = pd.DataFrame()

for i in an_exercicio:
    for j in no_anexo_rgf:
        df = RGF(i, in_periodicidade, nr_periodo_rgf, j, co_poder, id_ente)
        rgf_df = pd.concat([rgf_df, df])

In [12]:
rgf_df.sample(5)

,exercicio,periodo,periodicidade,instituicao,cod_ibge,uf,co_poder,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor
23,2020,3,Q,Governo do Estado do Rio Grande do Sul,43,RS,E,11377239,RGF-Anexo 01,E,Padrão,<MR-2>,DespesaComPessoalAtivoBruta,Pessoal Ativo,2.370801e+09
41,2023,3,Q,Governo do Estado do Rio Grande do Sul,43,RS,E,11466630,RGF-Anexo 01,E,Padrão,INSCRITAS EM RESTOS A PAGAR NÃO PROCESSADOS (b),VencimentosVantagensEOutrasDespesasVariaveis,"Vencimentos, Vantagens e Outras Despesas Variá...",5.105987e+05
152,2022,3,Q,Governo do Estado do Rio Grande do Sul,43,RS,E,11466630,RGF-Anexo 01,E,Padrão,<MR-9>,DespesaComPessoalNaoComputadaExerciciosAnterio...,Despesas de Exercícios Anteriores de Período A...,3.247153e+07
38,2019,3,Q,Governo do Estado do Rio Grande do Sul,43,RS,E,11329605,RGF-Anexo 01,E,Padrão,<MR-1>,VencimentosVantagensEOutrasDespesasVariaveis,"Vencimentos, Vantagens e Outras Despesas Variá...",7.920292e+08
4,2020,3,Q,Governo do Estado do Rio Grande do Sul,43,RS,E,11377239,RGF-Anexo 01,E,Padrão,<MR-7>,DespesaComPessoalBruta,DESPESA BRUTA COM PESSOAL (I),2.842299e+09

In [13]:
#Tratamento dos dados

rreo_df.loc[rreo_df['coluna'] == '% Aplicado Até o Bimestre', 'coluna'] = 'perc Aplicado Até o Bimestre'


rgf_df.loc[rgf_df['coluna'] == '% sobre a RCL Ajustada', 'coluna'] = 'perc sobre a RCL Ajustada'

def processar_dataframe(df):
    # Remove as colunas indesejadas
    df = df.drop(columns=df.columns[1:11])
    
    # Normaliza a coluna "coluna"
    df.loc[df['coluna'].str.contains('PREVISÃO ATUALIZADA', na=False), 'coluna'] = 'PREVISÃO ATUALIZADA'
        
    # Cria a tabela pivoteada
    df_pivot = df.pivot_table(index=['exercicio', 'cod_conta'], columns='coluna', values='valor', aggfunc='sum').fillna(0)

    return df_pivot

# Aplicação para os dois DataFrames
rreo_df_pivot = processar_dataframe(rreo_df)
rgf_df_pivot = processar_dataframe(rgf_df)

In [14]:
#funções de procura

def get_value(exercicio, cod_conta, coluna):
    try:
        return round(rreo_df_pivot.loc[(exercicio, cod_conta), coluna] / 1_000_000, 2)  # em milhões
    except KeyError:
        try:
            return round(rgf_df_pivot.loc[(exercicio, cod_conta), coluna] / 1_000_000, 2)  # em milhões
        except KeyError:
            return 0  # Retorna 0 caso a conta ou a coluna não existam em ambos os DataFrames
    
def format_negative(x):
    if isinstance(x, (int, float)):
        if x < 0:
            return f"({abs(x)})"
        return str(x)
    return x

In [15]:
#Tabela 1: Balanço Orçamentário da Receita e Deduções

exercicio_anterior = exercicio - 1

tabela_1 = pd.DataFrame({
    'RECEITAS': [
        'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)',
        'IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA',
        'CONTRIBUIÇÕES',
        'RECEITA PATRIMONIAL',
        'RECEITA AGROPECUÁRIA',
        'RECEITA INDUSTRIAL',
        'RECEITA DE SERVIÇOS',
        'TRANSFERÊNCIAS CORRENTES',
        'OUTRAS RECEITAS CORRENTES',
        'DEDUÇÕES',
        '( - ) Deduções para o FUNDEB',
        '( - ) Deduções para os Municípios',
        '( - ) Demais Deduções',
        'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)',
        'OPERAÇÕES DE CRÉDITO',
        'ALIENAÇÃO DE BENS',
        'AMORTIZAÇÕES DE EMPRÉSTIMOS',
        'TRANSFERÊNCIAS DE CAPITAL',
        'OUTRAS RECEITAS DE CAPITAL',
        'SUBTOTAL DAS RECEITAS',
        'OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO',
        'TOTAL DAS RECEITAS (LÍQUIDA)'                      
    ],
    'PREVISÃO ATUALIZADA (A)': [
        0,
        get_value(exercicio, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ReceitaDeContribuicoes', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ReceitaPatrimonial', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ReceitaAgropecuaria', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ReceitaIndustrial', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ReceitaDeServicos', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'RREO3TransferenciasCorrentes', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'OutrasReceitasCorrentes', 'PREVISÃO ATUALIZADA'),
        0,
        -get_value(exercicio, 'DeducaoDeReceitaParaFormacaoDoFUNDEB', 'PREVISÃO ATUALIZADA'),
        -get_value(exercicio, 'ReceitaDeTransferenciasConstitucionaisELegais', 'PREVISÃO ATUALIZADA'),
        0, #Verificar cod_conta Demais Deduções
        0,
        get_value(exercicio, 'ReceitasDeOperacoesDeCredito', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'AlienacaoDeBens', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'AmortizacoesDeEmprestimos', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'TransferenciasDeCapital', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'OutrasReceitasDeCapital', 'PREVISÃO ATUALIZADA'),
        0,
        0, #Verificar cod_conta para OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO
        0
    ],
    f'ARRECADADO (B) {exercicio}': [
        0,
        get_value(exercicio, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'ReceitaDeContribuicoes', 'Até o Bimestre (c)'),
        get_value(exercicio, 'ReceitaPatrimonial', 'Até o Bimestre (c)'),
        get_value(exercicio, 'ReceitaAgropecuaria', 'Até o Bimestre (c)'),
        get_value(exercicio, 'ReceitaIndustrial', 'Até o Bimestre (c)'),
        get_value(exercicio, 'ReceitaDeServicos', 'Até o Bimestre (c)'),
        get_value(exercicio, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'OutrasReceitasCorrentes', 'Até o Bimestre (c)'),
        0,
        -get_value(exercicio, 'DeducaoDeReceitaParaFormacaoDoFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        -get_value(exercicio, 'ReceitaDeTransferenciasConstitucionaisELegais', 'TOTAL (ÚLTIMOS 12 MESES)'),
        0, #Verificar cod_conta Demais Deduções
        0,
        get_value(exercicio, 'ReceitasDeOperacoesDeCredito', 'Até o Bimestre (c)'),
        get_value(exercicio, 'AlienacaoDeBens', 'Até o Bimestre (c)'),
        get_value(exercicio, 'AmortizacoesDeEmprestimos', 'Até o Bimestre (c)'),
        get_value(exercicio, 'TransferenciasDeCapital', 'Até o Bimestre (c)'),
        get_value(exercicio, 'OutrasReceitasDeCapital', 'Até o Bimestre (c)'),
        0,
        0, #Verificar cod_conta para OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO
        0                
    ],
    '% (C) = B/A': [0] * 22,
    f'{exercicio_anterior} (D)': [
        0,
        get_value(exercicio_anterior, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'ReceitaDeContribuicoes', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'ReceitaPatrimonial', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'ReceitaAgropecuaria', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'ReceitaIndustrial', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'ReceitaDeServicos', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'OutrasReceitasCorrentes', 'Até o Bimestre (c)'),
        0,
        -get_value(exercicio_anterior, 'DeducaoDeReceitaParaFormacaoDoFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        -get_value(exercicio_anterior, 'ReceitaDeTransferenciasConstitucionaisELegais', 'TOTAL (ÚLTIMOS 12 MESES)'),
        0, #Verificar cod_conta Demais Deduções
        0,
        get_value(exercicio_anterior, 'ReceitasDeOperacoesDeCredito', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'AlienacaoDeBens', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'AmortizacoesDeEmprestimos', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'TransferenciasDeCapital', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'OutrasReceitasDeCapital', 'Até o Bimestre (c)'),
        0,
        0, #Verificar cod_conta para OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO
        0                
    ],
    'Var. Nom. (%) E = (B/D) -1': [0] * 22
})

# calcula somas
tabela_1.loc[tabela_1['RECEITAS'] == 'DEDUÇÕES', 'PREVISÃO ATUALIZADA (A)'] = tabela_1.loc[9:12, 'PREVISÃO ATUALIZADA (A)'].sum()
tabela_1.loc[tabela_1['RECEITAS'] == 'DEDUÇÕES', f'ARRECADADO (B) {exercicio}'] = tabela_1.loc[9:12, f'ARRECADADO (B) {exercicio}'].sum()
tabela_1.loc[tabela_1['RECEITAS'] == 'DEDUÇÕES', f'{exercicio_anterior} (D)'] = tabela_1.loc[9:12, f'{exercicio_anterior} (D)'].sum()

tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', 'PREVISÃO ATUALIZADA (A)'] = (tabela_1.loc[1:11, 'PREVISÃO ATUALIZADA (A)'].sum()-
                                                                                                                      tabela_1.loc[tabela_1['RECEITAS'] == 'DEDUÇÕES', 'PREVISÃO ATUALIZADA (A)'].values[0]).round(2)
tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', f'ARRECADADO (B) {exercicio}'] = (tabela_1.loc[1:11, f'ARRECADADO (B) {exercicio}'].sum()-
                                                                                                                          tabela_1.loc[tabela_1['RECEITAS'] == 'DEDUÇÕES', f'ARRECADADO (B) {exercicio}'].values[0]).round(2)
tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', f'{exercicio_anterior} (D)'] = (tabela_1.loc[1:11, f'{exercicio_anterior} (D)'].sum()-
                                                                                                                        tabela_1.loc[tabela_1['RECEITAS'] == 'DEDUÇÕES', f'{exercicio_anterior} (D)'].values[0]).round(2)

tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)', 'PREVISÃO ATUALIZADA (A)'] = tabela_1.loc[14:20, 'PREVISÃO ATUALIZADA (A)'].sum().round(2)
tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)', f'ARRECADADO (B) {exercicio}'] = tabela_1.loc[14:20, f'ARRECADADO (B) {exercicio}'].sum().round(2)
tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)', f'{exercicio_anterior} (D)'] = tabela_1.loc[14:20, f'{exercicio_anterior} (D)'].sum().round(2)

tabela_1.loc[tabela_1['RECEITAS'] == 'SUBTOTAL DAS RECEITAS', 'PREVISÃO ATUALIZADA (A)'] = (
    tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', 'PREVISÃO ATUALIZADA (A)'].values[0]
    + tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)', 'PREVISÃO ATUALIZADA (A)'].values[0]
    ).round(2)
tabela_1.loc[tabela_1['RECEITAS'] == 'SUBTOTAL DAS RECEITAS', f'ARRECADADO (B) {exercicio}'] = (
    tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', f'ARRECADADO (B) {exercicio}'].values[0]
    + tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)', f'ARRECADADO (B) {exercicio}'].values[0]
    ).round(2)
tabela_1.loc[tabela_1['RECEITAS'] == 'SUBTOTAL DAS RECEITAS', f'{exercicio_anterior} (D)'] = (
    tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', f'{exercicio_anterior} (D)'].values[0]
    + tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)', f'{exercicio_anterior} (D)'].values[0]
    ).round(2)

tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', 'PREVISÃO ATUALIZADA (A)'] = (
    tabela_1.loc[tabela_1['RECEITAS'] == 'SUBTOTAL DAS RECEITAS', 'PREVISÃO ATUALIZADA (A)'].values[0]
    + tabela_1.loc[tabela_1['RECEITAS'] == 'OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO', 'PREVISÃO ATUALIZADA (A)'].values[0]
)
tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'ARRECADADO (B) {exercicio}'] = (
    tabela_1.loc[tabela_1['RECEITAS'] == 'SUBTOTAL DAS RECEITAS', f'ARRECADADO (B) {exercicio}'].values[0]
    + tabela_1.loc[tabela_1['RECEITAS'] == 'OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO', f'ARRECADADO (B) {exercicio}'].values[0]
)
tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'{exercicio_anterior} (D)'] = (
    tabela_1.loc[tabela_1['RECEITAS'] == 'SUBTOTAL DAS RECEITAS', f'{exercicio_anterior} (D)'].values[0]
    + tabela_1.loc[tabela_1['RECEITAS'] == 'OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO', f'{exercicio_anterior} (D)'].values[0]
)

# calcula a porcentagem das colunas
tabela_1['% (C) = B/A'] = (tabela_1[f'ARRECADADO (B) {exercicio}'] / tabela_1['PREVISÃO ATUALIZADA (A)'] * 100).round(2)
tabela_1['% (C) = B/A'] = tabela_1['% (C) = B/A'].fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_1['Var. Nom. (%) E = (B/D) -1'] = (
    abs((tabela_1[f'ARRECADADO (B) {exercicio}'] / tabela_1[f'{exercicio_anterior} (D)']) - 1) * 100
)
tabela_1['Var. Nom. (%) E = (B/D) -1'] = tabela_1['Var. Nom. (%) E = (B/D) -1'].round(2).fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

for col in ['PREVISÃO ATUALIZADA (A)', f'ARRECADADO (B) {exercicio}', f'{exercicio_anterior} (D)']:
    tabela_1[col] = tabela_1[col].apply(format_negative)

tabela_1

,RECEITAS,PREVISÃO ATUALIZADA (A),ARRECADADO (B) 2024,% (C) = B/A,2023 (D),Var. Nom. (%) E = (B/D) -1
0,RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS),60216.22,64089.31,106.43 %,60574.55,5.8 %
1,"IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA",59706.44,64337.57,107.76 %,57620.3,11.66 %
2,CONTRIBUIÇÕES,6007.37,6000.24,99.88 %,5484.01,9.41 %
3,RECEITA PATRIMONIAL,1926.76,1933.11,100.33 %,4117.91,53.06 %
4,RECEITA AGROPECUÁRIA,1.3,0.22,16.92 %,0.37,40.54 %
5,RECEITA INDUSTRIAL,0.01,0.0,0.0 %,0.0,0.0 %
6,RECEITA DE SERVIÇOS,603.98,593.19,98.21 %,559.58,6.01 %
7,TRANSFERÊNCIAS CORRENTES,14335.99,14873.57,103.75 %,14607.13,1.82 %
8,OUTRAS RECEITAS CORRENTES,1070.79,1479.58,138.18 %,1109.91,33.31 %
9,DEDUÇÕES,(23436.42),(25128.17),107.22 %,(22924.66),9.61 %
10,( - ) Deduções para o FUNDEB,(8782.93),(9464.51),107.76 %,(8585.32),10.24 %
11,( - ) Deduções para os Municípios,(14653.49),(15663.66),106.89 %,(14339.34),9.24 %
12,( - ) Demais Deduções,0.0,0.0,0.0 %,0.0,0.0 %
13,RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS),2902.18,1485.71,51.19 %,4325.02,65.65 %
14,OPERAÇÕES DE CRÉDITO,2580.35,1221.37,47.33 %,78.66,1452.72 %
15,ALIENAÇÃO DE BENS,109.49,42.64,38.94 %,4008.9,98.94 %
16,AMORTIZAÇÕES DE EMPRÉSTIMOS,9.04,34.32,379.65 %,20.73,65.56 %
17,TRANSFERÊNCIAS DE CAPITAL,194.7,186.76,95.92 %,186.7,0.03 %
18,OUTRAS RECEITAS DE CAPITAL,8.6,0.62,7.21 %,30.03,97.94 %
19,SUBTOTAL DAS RECEITAS,63118.4,65575.02,103.89 %,64899.57,1.04 %
20,OPERAÇÕES DE CRÉDITO/REFINANCIAMENTO,0.0,0.0,0.0 %,0.0,0.0 %
21,TOTAL DAS RECEITAS (LÍQUIDA),63118.4,65575.02,103.89 %,64899.57,1.04 %

In [16]:
#Tabela_2: Receitas Tributárias Líquidas


tabela_2 = pd.DataFrame({
    'RECEITAS': [
        'IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA',
        'ICMS',
        'IPVA',
        'ITCD',
        'IRRF',
        'Outras Receitas Tributárias',
        '(-) Deduções dos Impostos',
        'TOTAL DAS RECEITAS (LÍQUIDA)'
    ],
    'PREVISÃO ATUALIZADA (A)' : [
        get_value(exercicio, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ICMSLiquidoExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'IPVALiquidoExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ITCDLiquidoExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'IRRFLiquidoExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'OutrasReceitasTributarias', 'PREVISÃO ATUALIZADA'), #taxas
        0, #Deduções
        0, #RECEITAS LIQUIDAS
    ],
    f'ARRECADADO (B) {exercicio}' :[
        get_value(exercicio, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'ICMSLiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'IPVALiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'ITCDLiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'IRRFLiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'OutrasReceitasTributarias', 'TOTAL (ÚLTIMOS 12 MESES)'), #taxas
        0, #Deduções
        0, #RECEITAS LIQUIDAS
    ],
    '% (C) = B/A': [0] * 8,
    f'{exercicio_anterior} (D)' :[
        get_value(exercicio_anterior, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'ICMSLiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'IPVALiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'ITCDLiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'IRRFLiquidoExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'OutrasReceitasTributarias', 'TOTAL (ÚLTIMOS 12 MESES)'), #taxas
        0, #Deduções
        0, #RECEITAS LIQUIDAS
    ]
    })


#Total das Deduções - 
tabela_2.loc[tabela_2['RECEITAS'] == '(-) Deduções dos Impostos', 'PREVISÃO ATUALIZADA (A)'] = (
    -get_value(exercicio, 'DeducaoDeReceitaParaFormacaoDoFUNDEB', 'PREVISÃO ATUALIZADA')
    -get_value(exercicio, 'ReceitaDeTransferenciasConstitucionaisELegais', 'PREVISÃO ATUALIZADA')
)
tabela_2.loc[tabela_2['RECEITAS'] == '(-) Deduções dos Impostos', f'ARRECADADO (B) {exercicio}'] = (
    -get_value(exercicio, 'DeducaoDeReceitaParaFormacaoDoFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)') 
    -get_value(exercicio, 'ReceitaDeTransferenciasConstitucionaisELegais', 'TOTAL (ÚLTIMOS 12 MESES)')   
)
tabela_2.loc[tabela_2['RECEITAS'] == '(-) Deduções dos Impostos', f'{exercicio_anterior} (D)'] = (
    -get_value(exercicio_anterior, 'DeducaoDeReceitaParaFormacaoDoFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)')
    -get_value(exercicio_anterior, 'ReceitaDeTransferenciasConstitucionaisELegais', 'TOTAL (ÚLTIMOS 12 MESES)')    
)



#Total da Receita Líquida
tabela_2.loc[tabela_2['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', 'PREVISÃO ATUALIZADA (A)'] = (
    tabela_2.loc[tabela_2['RECEITAS'] == 'IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA', 'PREVISÃO ATUALIZADA (A)'].values[0]
    + tabela_2.loc[tabela_2['RECEITAS'] == '(-) Deduções dos Impostos', 'PREVISÃO ATUALIZADA (A)'].values[0]
).round(2)
tabela_2.loc[tabela_2['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'ARRECADADO (B) {exercicio}'] = (
    tabela_2.loc[tabela_2['RECEITAS'] == 'IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA', f'ARRECADADO (B) {exercicio}'].values[0]
    + tabela_2.loc[tabela_2['RECEITAS'] == '(-) Deduções dos Impostos', f'ARRECADADO (B) {exercicio}'].values[0]
).round(2)
tabela_2.loc[tabela_2['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'{exercicio_anterior} (D)'] = (
    tabela_2.loc[tabela_2['RECEITAS'] == 'IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA', f'{exercicio_anterior} (D)'].values[0]
    + tabela_2.loc[tabela_2['RECEITAS'] == '(-) Deduções dos Impostos', f'{exercicio_anterior} (D)'].values[0]
).round(2)

# calcula a porcentagem das colunas
tabela_2['% (C) = B/A'] = (tabela_2[f'ARRECADADO (B) {exercicio}'] / tabela_2['PREVISÃO ATUALIZADA (A)'] * 100).round(2)
tabela_2['% (C) = B/A'] = tabela_2['% (C) = B/A'].fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_2['Var. Nom. (%) E = (B/D) -1'] = ((tabela_2[f'ARRECADADO (B) {exercicio}'] / tabela_2[f'{exercicio_anterior} (D)']) - 1) * 100
tabela_2['Var. Nom. (%) E = (B/D) -1'] = tabela_2['Var. Nom. (%) E = (B/D) -1'].round(2).fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'


for col in ['PREVISÃO ATUALIZADA (A)', f'ARRECADADO (B) {exercicio}', f'{exercicio_anterior} (D)']:
    tabela_2[col] = tabela_2[col].apply(format_negative)


tabela_2

,RECEITAS,PREVISÃO ATUALIZADA (A),ARRECADADO (B) 2024,% (C) = B/A,2023 (D),Var. Nom. (%) E = (B/D) -1
0,"IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA",59706.44,64337.57,107.76 %,57620.3,11.66 %
1,ICMS,46870.0,50610.92,107.98 %,44865.77,12.81 %
2,IPVA,5234.0,5478.86,104.68 %,5109.58,7.23 %
3,ITCD,1129.0,1656.5,146.72 %,1430.89,15.77 %
4,IRRF,3872.11,3810.31,98.4 %,3631.76,4.92 %
5,Outras Receitas Tributárias,2601.33,2780.98,106.91 %,2582.31,7.69 %
6,(-) Deduções dos Impostos,(23436.42),(25128.17),107.22 %,(22924.66),9.61 %
7,TOTAL DAS RECEITAS (LÍQUIDA),36270.02,39209.4,108.1 %,34695.64,13.01 %

In [17]:
# Tabela 3: Transferências Correntes

tabela_3 = pd.DataFrame({
    'RECEITAS': [
        'Transferências Correntes',
        'Cota-Parte do Fundo de Participação dos Estados e do Distrito Federal - FPE',
        'IPI-Exportação',
        'FUNDEB',
        'Outras Transferências Correntes',
        '(-) Deduções das Transferências Correntes',
        'TRANSFERÊNCIAS CORRENTES LÍQUIDAS'
    ],
    'PREVISÃO ATUALIZADA (A)': [
        get_value(exercicio, 'RREO3TransferenciasCorrentes', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'RREO3CotaParteDoFPE', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'RREO3TransferenciasDaLC611989', 'PREVISÃO ATUALIZADA'), # IPI
        get_value(exercicio, 'RREO3TransferenciasDoFUNDEB', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'RREO3OutrasTransferenciasCorrentes', 'PREVISÃO ATUALIZADA'),
        0,  # Deduções
        get_value(exercicio, 'RREO6TransferenciasCorrentes', 'PREVISÃO ATUALIZADA'),   # Transferências Correntes
    ],
    f'ARRECADADO (B) {exercicio}': [
        get_value(exercicio, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'RREO3CotaParteDoFPE', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'RREO3TransferenciasDaLC611989', 'TOTAL (ÚLTIMOS 12 MESES)'), # IPI
        get_value(exercicio, 'RREO3TransferenciasDoFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'RREO3OutrasTransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
        0,  # Deduções
        get_value(exercicio, 'RREO6TransferenciasCorrentes', 'RECEITAS REALIZADAS (a)')   # Transferências Correntes
    ],
    '% (C) = B/A': [0] * 7,
    f'{exercicio_anterior} (D)': [
        get_value(exercicio_anterior, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'RREO3CotaParteDoFPE', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'RREO3TransferenciasDaLC611989', 'TOTAL (ÚLTIMOS 12 MESES)'), # IPI
        get_value(exercicio_anterior, 'RREO3TransferenciasDoFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'RREO3OutrasTransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
        0,  # Deduções
        get_value(exercicio_anterior, 'RREO6TransferenciasCorrentes', 'RECEITAS REALIZADAS (a)')   # Transferências Correntes
    ]
})

# calculo deduções utilizando a diferença entre as contas, verificar as contas respectivas
tabela_3.loc[tabela_3['RECEITAS'] == '(-) Deduções das Transferências Correntes', 'PREVISÃO ATUALIZADA (A)'] = -(
    get_value(exercicio, 'RREO3TransferenciasCorrentes', 'PREVISÃO ATUALIZADA')
    -get_value(exercicio, 'RREO6TransferenciasCorrentes', 'PREVISÃO ATUALIZADA')
).round(2)
tabela_3.loc[tabela_3['RECEITAS'] == '(-) Deduções das Transferências Correntes', f'ARRECADADO (B) {exercicio}'] = -(
    get_value(exercicio, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)')
    -get_value(exercicio, 'RREO6TransferenciasCorrentes', 'RECEITAS REALIZADAS (a)')
).round(2)
tabela_3.loc[tabela_3['RECEITAS'] == '(-) Deduções das Transferências Correntes', f'{exercicio_anterior} (D)'] = -(
    get_value(exercicio_anterior, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)')
    -get_value(exercicio_anterior, 'RREO6TransferenciasCorrentes', 'RECEITAS REALIZADAS (a)')
).round(2)



# calulo porcentagens
tabela_3['% (C) = B/A'] = (tabela_3[f'ARRECADADO (B) {exercicio}'] / tabela_3['PREVISÃO ATUALIZADA (A)'] * 100).round(2)
tabela_3['% (C) = B/A'] = tabela_3['% (C) = B/A'].fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_3['Var. Nom. (%) E = (B/D) -1'] = ((tabela_3[f'ARRECADADO (B) {exercicio}'] / tabela_3[f'{exercicio_anterior} (D)']) - 1) * 100
tabela_3['Var. Nom. (%) E = (B/D) -1'] = tabela_3['Var. Nom. (%) E = (B/D) -1'].round(2).fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

# formato negativo numeros
for col in ['PREVISÃO ATUALIZADA (A)', f'ARRECADADO (B) {exercicio}', f'{exercicio_anterior} (D)']:
    tabela_3[col] = tabela_3[col].apply(format_negative)


tabela_3

,RECEITAS,PREVISÃO ATUALIZADA (A),ARRECADADO (B) 2024,% (C) = B/A,2023 (D),Var. Nom. (%) E = (B/D) -1
0,Transferências Correntes,14335.99,14873.57,103.75 %,14607.13,1.82 %
1,Cota-Parte do Fundo de Participação dos Estado...,3702.47,3770.73,101.84 %,3209.47,17.49 %
2,IPI-Exportação,478.09,644.97,134.91 %,436.86,47.64 %
3,FUNDEB,6189.71,6431.8,103.91 %,5844.69,10.05 %
4,Outras Transferências Correntes,3965.73,4026.08,101.52 %,5116.1,-21.31 %
5,(-) Deduções das Transferências Correntes,(1480.82),(1295.43),87.48 %,(1756.14),-26.23 %
6,TRANSFERÊNCIAS CORRENTES LÍQUIDAS,12855.17,13578.14,105.62 %,12850.99,5.66 %

In [18]:
# Tabela 4: Receitas de Capital

tabela_4 = pd.DataFrame({
    'RECEITAS': [
        'RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)',
        'OPERAÇÕES DE CRÉDITO',
        'Operações de Crédito Internas',
        'Operações de Crédito Externas',
        'ALIENAÇÃO DE BENS',
        'AMORTIZAÇÕES DE EMPRÉSTIMOS',
        'TRANSFERÊNCIAS DE CAPITAL',
        'Transferências da União e de suas Entidades',
        'Demais Transferências de Capital',
        'OUTRAS RECEITAS DE CAPITAL',
    ],
    'PREVISÃO ATUALIZADA (A)': [
        get_value(exercicio, 'ReceitasDeCapital','PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'ReceitasDeOperacoesDeCredito', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'OperacoesDeCreditoInternas', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'OperacoesDeCreditoExternas', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'AlienacaoDeBens', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'AmortizacoesDeEmprestimos', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'TransferenciasDeCapital', 'PREVISÃO ATUALIZADA'),
        get_value(exercicio, 'TransferenciasDeCapitalDaUniaoEDeSuasEntidades', 'PREVISÃO ATUALIZADA'),
        (get_value(exercicio, 'TransferenciasDeCapitalDosEstadosEDoDistritoFederalEDeSuasEntidades', 'PREVISÃO ATUALIZADA')
         +get_value(exercicio, 'TransferenciasDeCapitalDeInstituicoesPrivadas', 'PREVISÃO ATUALIZADA')
         +get_value(exercicio, 'TransferenciasDeCapitalDeOutrasInstituicoesPublicas', 'PREVISÃO ATUALIZADA')
         +get_value(exercicio, 'TransferenciasDeCapitalDoExterior', 'PREVISÃO ATUALIZADA')),
        get_value(exercicio, 'OutrasReceitasDeCapital', 'PREVISÃO ATUALIZADA'),
    ],
    f'ARRECADADO (B) {exercicio}': [
        get_value(exercicio, 'ReceitasDeCapital','Até o Bimestre (c)'),
        get_value(exercicio, 'ReceitasDeOperacoesDeCredito', 'Até o Bimestre (c)'),
        get_value(exercicio, 'OperacoesDeCreditoInternas', 'Até o Bimestre (c)'),
        get_value(exercicio, 'OperacoesDeCreditoExternas', 'Até o Bimestre (c)'),
        get_value(exercicio, 'AlienacaoDeBens', 'Até o Bimestre (c)'),
        get_value(exercicio, 'AmortizacoesDeEmprestimos', 'Até o Bimestre (c)'),
        get_value(exercicio, 'TransferenciasDeCapital', 'Até o Bimestre (c)'),
        get_value(exercicio, 'TransferenciasDeCapitalDaUniaoEDeSuasEntidades', 'Até o Bimestre (c)'),
        (get_value(exercicio, 'TransferenciasDeCapitalDosEstadosEDoDistritoFederalEDeSuasEntidades', 'Até o Bimestre (c)')
         +get_value(exercicio, 'TransferenciasDeCapitalDeInstituicoesPrivadas', 'Até o Bimestre (c)')
         +get_value(exercicio, 'TransferenciasDeCapitalDeOutrasInstituicoesPublicas', 'Até o Bimestre (c)')
         +get_value(exercicio, 'TransferenciasDeCapitalDoExterior', 'Até o Bimestre (c)')),
        get_value(exercicio, 'OutrasReceitasDeCapital', 'Até o Bimestre (c)'),
    ],
    '% (C) = B/A': [0] * 10,
    f'{exercicio_anterior} (D)': [
        get_value(exercicio_anterior, 'ReceitasDeCapital', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'ReceitasDeOperacoesDeCredito', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'OperacoesDeCreditoInternas', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'OperacoesDeCreditoExternas', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'AlienacaoDeBens', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'AmortizacoesDeEmprestimos', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'TransferenciasDeCapital', 'Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'TransferenciasDeCapitalDaUniaoEDeSuasEntidades', 'Até o Bimestre (c)'),
        (get_value(exercicio_anterior, 'TransferenciasDeCapitalDosEstadosEDoDistritoFederalEDeSuasEntidades', 'Até o Bimestre (c)')
         +get_value(exercicio_anterior, 'TransferenciasDeCapitalDeInstituicoesPrivadas', 'Até o Bimestre (c)')
         +get_value(exercicio_anterior, 'TransferenciasDeCapitalDeOutrasInstituicoesPublicas', 'Até o Bimestre (c)')
         +get_value(exercicio_anterior, 'TransferenciasDeCapitalDoExterior', 'Até o Bimestre (c)')),
        get_value(exercicio_anterior, 'OutrasReceitasDeCapital', 'Até o Bimestre (c)'),
    ],
    'Var. Nom. (%) E = (B/D) -1': [0] * 10
})


# calcula a porcentagem das colunas
tabela_4['% (C) = B/A'] = (tabela_4[f'ARRECADADO (B) {exercicio}'] / tabela_4['PREVISÃO ATUALIZADA (A)'] * 100).round(2)
tabela_4['% (C) = B/A'] = tabela_4['% (C) = B/A'].fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_4['Var. Nom. (%) E = (B/D) -1'] = (
    abs((tabela_4[f'ARRECADADO (B) {exercicio}'] / tabela_4[f'{exercicio_anterior} (D)']) - 1) * 100
)
tabela_4['Var. Nom. (%) E = (B/D) -1'] = tabela_4['Var. Nom. (%) E = (B/D) -1'].round(2).fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_4

,RECEITAS,PREVISÃO ATUALIZADA (A),ARRECADADO (B) 2024,% (C) = B/A,2023 (D),Var. Nom. (%) E = (B/D) -1
0,RECEITAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS),2902.17,1485.71,51.19 %,4325.02,65.65 %
1,OPERAÇÕES DE CRÉDITO,2580.35,1221.37,47.33 %,78.66,1452.72 %
2,Operações de Crédito Internas,0.00,0.00,0.0 %,0.00,0.0 %
3,Operações de Crédito Externas,2580.35,1221.37,47.33 %,78.66,1452.72 %
4,ALIENAÇÃO DE BENS,109.49,42.64,38.94 %,4008.90,98.94 %
5,AMORTIZAÇÕES DE EMPRÉSTIMOS,9.04,34.32,379.65 %,20.73,65.56 %
6,TRANSFERÊNCIAS DE CAPITAL,194.70,186.76,95.92 %,186.70,0.03 %
7,Transferências da União e de suas Entidades,194.09,183.07,94.32 %,185.79,1.46 %
8,Demais Transferências de Capital,0.54,2.38,440.74 %,0.36,561.11 %
9,OUTRAS RECEITAS DE CAPITAL,8.60,0.62,7.21 %,30.03,97.94 %

In [19]:
# Tabela 5: Balanço Orçamentário da Despesa

tabela_5 = pd.DataFrame({
    'DESPESAS': [
        'DESPESAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)',
        'Pessoal e Encargos Sociais',
        'Juros e Encargos da Dívida',
        'Outras Despesas Correntes',
        'DESPESAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS)',
        'Investimentos',
        'Inversões Financeiras',
        'Amortização da Dívida',
        'TOTAL DAS DESPESAS'
    ],
    'DOTAÇÃO ATUALIZADA (A)': [
        get_value(exercicio, 'DespesasCorrentes','DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'PessoalEEncargosSociais', 'DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'JurosEEncargosDaDivida', 'DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'OutrasDespesasCorrentes', 'DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'DespesasDeCapital', 'DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'Investimentos', 'DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'InversoesFinanceiras', 'DOTAÇÃO ATUALIZADA (e)'),
        get_value(exercicio, 'AmortizacaoDaDivida', 'DOTAÇÃO ATUALIZADA (e)'),
        0
    ],
    f'EMPENHADO {exercicio} (B)': [
        get_value(exercicio, 'DespesasCorrentes','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'PessoalEEncargosSociais', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'JurosEEncargosDaDivida', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'OutrasDespesasCorrentes', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'DespesasDeCapital', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'Investimentos', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'InversoesFinanceiras', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio, 'AmortizacaoDaDivida', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        0
    ],
    '% (C) = B/A': [0] * 9,
    f'EMPENHADO {exercicio_anterior} (D)': [
        get_value(exercicio_anterior, 'DespesasCorrentes', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'PessoalEEncargosSociais', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'JurosEEncargosDaDivida', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'OutrasDespesasCorrentes', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'DespesasDeCapital', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'Investimentos', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'InversoesFinanceiras', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        get_value(exercicio_anterior, 'AmortizacaoDaDivida', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        0
    ],
    'Var. Nom. (%) E = (B/D) -1': [0] * 9
})

tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', 'DOTAÇÃO ATUALIZADA (A)'] = (
    get_value(exercicio, 'DespesasCorrentes','DOTAÇÃO ATUALIZADA (e)')
    +get_value(exercicio, 'DespesasDeCapital', 'DOTAÇÃO ATUALIZADA (e)')
)
tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio} (B)'] = (
    get_value(exercicio, 'DespesasCorrentes', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)')
    +get_value(exercicio, 'DespesasDeCapital', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)')
)
tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio_anterior} (D)'] = (
    get_value(exercicio_anterior, 'DespesasCorrentes', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)')
    +get_value(exercicio_anterior, 'DespesasDeCapital', 'DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)')
)


# calcula a porcentagem das colunas
tabela_5['% (C) = B/A'] = (tabela_5[f'EMPENHADO {exercicio} (B)'] / tabela_5['DOTAÇÃO ATUALIZADA (A)'] * 100).round(2)
tabela_5['% (C) = B/A'] = tabela_5['% (C) = B/A'].fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_5['Var. Nom. (%) E = (B/D) -1'] = (
    abs((tabela_5[f'EMPENHADO {exercicio} (B)'] / tabela_5[f'EMPENHADO {exercicio_anterior} (D)']) - 1) * 100
)
tabela_5['Var. Nom. (%) E = (B/D) -1'] = tabela_5['Var. Nom. (%) E = (B/D) -1'].round(2).fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_5

,DESPESAS,DOTAÇÃO ATUALIZADA (A),EMPENHADO 2024 (B),% (C) = B/A,EMPENHADO 2023 (D),Var. Nom. (%) E = (B/D) -1
0,DESPESAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS),68217.37,57926.57,84.91 %,55244.65,4.85 %
1,Pessoal e Encargos Sociais,43653.92,36977.99,84.71 %,36001.37,2.71 %
2,Juros e Encargos da Dívida,995.75,852.76,85.64 %,1471.99,42.07 %
3,Outras Despesas Correntes,23567.70,20095.82,85.27 %,17771.30,13.08 %
4,DESPESAS DE CAPITAL (EXCETO INTRA-ORÇAMENTÁRIAS),9941.53,6812.80,68.53 %,5933.66,14.82 %
5,Investimentos,7477.88,4948.99,66.18 %,2975.16,66.34 %
6,Inversões Financeiras,1490.65,1479.70,99.27 %,2294.42,35.51 %
7,Amortização da Dívida,972.99,384.12,39.48 %,664.08,42.16 %
8,TOTAL DAS DESPESAS,78158.90,64739.37,82.83 %,61178.31,5.82 %

In [ ]:
rgf_df_pivot.sample(2)

In [ ]:
#Tabela Indicadores

tabela_indicadores = pd.DataFrame({
    'INDICADOR': [
        'Receita Total',
        'Despesa Total',
        'Resultado Orçamentário Total',
        'Receita Total Efetiva',
        'Despesa Total Efetiva',
        'Resultado Orçamentário Efetivo',
        'Receita Primária (sem RPPS)',
        'Despesa Primária (sem RPPS)',
        'Resultado Primário (sem RPPS)',
        'Receita Corrente Líquida',
        'Resultado Previdênciário',
        'Aplicação em Educação (% RCL)',
        'Aplicação em Saúde (% RCL)',
        'Limite LRF Dívida (DCL/RCL) (%)',
        'Limite LRF Desp. Pessoal Poder Executivo (%)',
        'Limite LRF Desp. Pessoal Todos os Poderes (%)',
        'Despesas Correntes/Receitas Correntes (%)',
    ],
    f'{exercicio}': [
        get_value(exercicio, 'TotalReceitas','Até o Bimestre (c)'),
        get_value(exercicio, 'TotalDespesas','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        (get_value(exercicio, 'TotalReceitas','Até o Bimestre (c)')
         -get_value(exercicio, 'TotalDespesas','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)')),
        float(tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'ARRECADADO (B) {exercicio}'].values[0]),
        float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio} (B)']),
        (float(tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'ARRECADADO (B) {exercicio}'].values[0])
         -float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio} (B)'])),
        get_value(exercicio, 'ReceitaPrimariaTotalExcetoFontesRPPS','RECEITAS REALIZADAS (a)'),
        get_value(exercicio, 'DespesaPrimariaTotalExcetoFontesRPPS','DESPESAS EMPENHADAS'), #Valor não validado
        get_value(exercicio, 'ResultadoPrimarioSemRPPSAcimaDaLinha','VALOR'),
        get_value(exercicio, 'RREO3ReceitaCorrenteLiquida','TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio, 'ResultadoPrevidenciarioRPPSPrevidenciarioDemonstrativoSimplificado','Até o Bimestre'), #não validado
        0, #verificar valor aplicado em educação
        rreo_df_pivot.loc[(exercicio, 'AplicacaoTotalDasDespesasComAcoesEServicosPublicosDeSaude'), 'perc Aplicado Até o Bimestre'],
        ((pd.to_numeric(get_value(exercicio, 'DividaConsolidadaLiquida',f'Até o Bimestre {exercicio} (b)'), errors='coerce') / pd.to_numeric(get_value(exercicio, 'RREO3ReceitaCorrenteLiquida','TOTAL (ÚLTIMOS 12 MESES)'), errors='coerce')) * 100).round(2),
        rgf_df_pivot.loc[(exercicio, 'DespesaComPessoalTotal'), 'perc sobre a RCL Ajustada'],
        0, #despesa pessoal consolidado verificar
        (pd.to_numeric(get_value(exercicio, 'DespesasCorrentes','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'), errors='coerce') / pd.to_numeric(tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', f'ARRECADADO (B) {exercicio}'].values[0], errors='coerce')),
    ],
    f'{exercicio_anterior}': [
        get_value(exercicio_anterior, 'TotalReceitas','Até o Bimestre (c)'),
        get_value(exercicio_anterior, 'TotalDespesas','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'),
        (get_value(exercicio_anterior, 'TotalReceitas','Até o Bimestre (c)')
         -get_value(exercicio_anterior, 'TotalDespesas','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)')),
        float(tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'{exercicio_anterior} (D)'].values[0]),
        float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio_anterior} (D)']),
        (float(tabela_1.loc[tabela_1['RECEITAS'] == 'TOTAL DAS RECEITAS (LÍQUIDA)', f'{exercicio_anterior} (D)'].values[0])
         -float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio_anterior} (D)'])),
        get_value(exercicio_anterior, 'ReceitaPrimariaTotalExcetoFontesRPPS','RECEITAS REALIZADAS (a)'),
        get_value(exercicio_anterior, 'DespesaPrimariaTotalExcetoFontesRPPS','DESPESAS EMPENHADAS'),
        get_value(exercicio_anterior, 'ResultadoPrimarioSemRPPSAcimaDaLinha','VALOR'),
        get_value(exercicio_anterior, 'RREO3ReceitaCorrenteLiquida','TOTAL (ÚLTIMOS 12 MESES)'),
        get_value(exercicio_anterior, 'ResultadoPrevidenciarioRPPSPrevidenciarioDemonstrativoSimplificado','Até o Bimestre'),
        0,
        rreo_df_pivot.loc[(exercicio_anterior, 'AplicacaoTotalDasDespesasComAcoesEServicosPublicosDeSaude'), 'perc Aplicado Até o Bimestre'],
        ((pd.to_numeric(get_value(exercicio_anterior, 'DividaConsolidadaLiquida',f'Até o Bimestre {exercicio_anterior} (b)'), errors='coerce') / pd.to_numeric(get_value(exercicio_anterior, 'RREO3ReceitaCorrenteLiquida','TOTAL (ÚLTIMOS 12 MESES)'), errors='coerce')) * 100).round(2),
        rgf_df_pivot.loc[(exercicio_anterior, 'DespesaComPessoalTotal'), 'perc sobre a RCL Ajustada'],
        0, #despesa pessoal consolidado
        (pd.to_numeric(get_value(exercicio_anterior, 'DespesasCorrentes','DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)'), errors='coerce') / pd.to_numeric(tabela_1.loc[tabela_1['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', f'{exercicio_anterior} (D)'].values[0], errors='coerce')),
    ],
    f'{exercicio}/{exercicio_anterior}': [0] * 17
})

tabela_indicadores[f'{exercicio}'] = pd.to_numeric(tabela_indicadores[f'{exercicio}'], errors='coerce')
tabela_indicadores[f'{exercicio_anterior}'] = pd.to_numeric(tabela_indicadores[f'{exercicio_anterior}'], errors='coerce')

tabela_indicadores[f'{exercicio}/{exercicio_anterior}'] = (
    (tabela_indicadores[f'{exercicio}'] / tabela_indicadores[f'{exercicio_anterior}'] - 1) * 100
).round(2).fillna(0).replace([float('inf'), -float('inf')], 0).astype(str) + ' %'

tabela_indicadores

C:\Users\00526862130\AppData\Local\Temp\ipykernel_23572\3233640509.py:29: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio} (B)']),
C:\Users\00526862130\AppData\Local\Temp\ipykernel_23572\3233640509.py:31: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  -float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio} (B)'])),
C:\Users\00526862130\AppData\Local\Temp\ipykernel_23572\3233640509.py:50: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio_anterior} (D)']),
C:\Users\00526862130\AppData\Local\Temp\ipykernel_23572\3233640509.py:52: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  -float(tabela_5.loc[tabela_5['DESPESAS'] == 'TOTAL DAS DESPESAS', f'EMPENHADO {exercicio_anterior} (D)'])),

,INDICADOR,2024,2023,2024/2023
0,Receita Total,82634.820000,81970.340000,0.81 %
1,Despesa Total,82012.420000,78352.530000,4.67 %
2,Resultado Orçamentário Total,622.400000,3617.810000,-82.8 %
3,Receita Total Efetiva,65575.020000,64899.570000,1.04 %
4,Despesa Total Efetiva,64739.370000,61178.310000,5.82 %
5,Resultado Orçamentário Efetivo,835.650000,3721.260000,-77.54 %
6,Receita Primária (sem RPPS),60213.180000,56351.670000,6.85 %
7,Despesa Primária (sem RPPS),0.000000,55675.310000,-100.0 %
8,Resultado Primário (sem RPPS),1734.080000,2483.770000,-30.18 %
9,Receita Corrente Líquida,60043.880000,56639.120000,6.01 %
10,Resultado Previdênciário,935.580000,886.620000,5.52 %
11,Aplicação em Educação (% RCL),0.000000,0.000000,0.0 %
12,Aplicação em Saúde (% RCL),12.150000,12.170000,-0.16 %
13,Limite LRF Dívida (DCL/RCL) (%),184.400000,185.210000,-0.44 %
14,Limite LRF Desp. Pessoal Poder Executivo (%),43.690000,45.030000,-2.98 %
15,Limite LRF Desp. Pessoal Todos os Poderes (%),0.000000,0.000000,0.0 %
16,Despesas Correntes/Receitas Correntes (%),0.903841,0.912011,-0.9 %

In [22]:
rreo_df.to_excel('rreo.xlsx')