In [2]:
import requests, json
import pandas as pd
import numpy as np

In [3]:
def RREO(an_exercicio, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente):
    url = f'https://apidatalake.tesouro.gov.br/ords/siconfi/tt//rreo?an_exercicio={an_exercicio}&nr_periodo={nr_periodo}&co_tipo_demonstrativo={co_tipo_demonstrativo}&no_anexo={no_anexo}&co_esfera=&id_ente={id_ente}'
    response = requests.get(url)
    if(response.status_code != 200): 
            return({result:'Falhou'})
    dados = response.json()
    return pd.DataFrame(dados['items'])

In [18]:
an_exercicio = ['2020','2021','2022','2023','2024']
id_ente = "11" #Código IBGE do Ente. rondonia 11 sao paulo 35
co_tipo_demonstrativo = 'RREO' #tipo de demonstrativo RREO - Bimestre
nr_periodo = '6' #periodo RREO - Bimestre
no_anexo = ['RREO-Anexo 01','RREO-Anexo 03']

rreo_df = pd.DataFrame()

for i in an_exercicio:
    for j in no_anexo:
        df = RREO(i, nr_periodo, co_tipo_demonstrativo, j, id_ente)
        rreo_df = pd.concat([rreo_df, df])

In [ ]:
#rreo_df.head(5)

,exercicio,demonstrativo,periodo,periodicidade,instituicao,cod_ibge,uf,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor
0,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,PREVISÃO INICIAL,ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),8.238173e+09
1,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,PREVISÃO ATUALIZADA (a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),9.213927e+09
2,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,No Bimestre (b),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.811558e+09
3,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,% (b/a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.966000e+01
4,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,Até o Bimestre (c),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),9.153014e+09

In [ ]:
#rreo_df.tail(5)

,exercicio,demonstrativo,periodo,periodicidade,instituicao,cod_ibge,uf,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor
378,2024,RREO,6,B,Governo do Estado de Rondônia,11,RO,1616379,RREO-Anexo 03,E,Padrão,<MR-2>,RREO3ReceitaCorrenteLiquidaAjustadaParaCalculo...,RECEITA CORRENTE LÍQUIDA AJUSTADA PARA CÁLCULO...,1.078293e+09
379,2024,RREO,6,B,Governo do Estado de Rondônia,11,RO,1616379,RREO-Anexo 03,E,Padrão,<MR-1>,RREO3ReceitaCorrenteLiquidaAjustadaParaCalculo...,RECEITA CORRENTE LÍQUIDA AJUSTADA PARA CÁLCULO...,1.197302e+09
380,2024,RREO,6,B,Governo do Estado de Rondônia,11,RO,1616379,RREO-Anexo 03,E,Padrão,<MR>,RREO3ReceitaCorrenteLiquidaAjustadaParaCalculo...,RECEITA CORRENTE LÍQUIDA AJUSTADA PARA CÁLCULO...,1.505784e+09
381,2024,RREO,6,B,Governo do Estado de Rondônia,11,RO,1616379,RREO-Anexo 03,E,Padrão,TOTAL (ÚLTIMOS 12 MESES),RREO3ReceitaCorrenteLiquidaAjustadaParaCalculo...,RECEITA CORRENTE LÍQUIDA AJUSTADA PARA CÁLCULO...,1.419033e+10
382,2024,RREO,6,B,Governo do Estado de Rondônia,11,RO,1616379,RREO-Anexo 03,E,Padrão,PREVISÃO ATUALIZADA 2024,RREO3ReceitaCorrenteLiquidaAjustadaParaCalculo...,RECEITA CORRENTE LÍQUIDA AJUSTADA PARA CÁLCULO...,1.412988e+10

In [ ]:
#rreo_df.sample(2)

,exercicio,demonstrativo,periodo,periodicidade,instituicao,cod_ibge,uf,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor
366,2020,RREO,6,B,Governo do Estado de São Paulo,35,SP,45919049,RREO-Anexo 03,E,Padrão,<MR-6>,RREO3ReceitaCorrenteLiquidaAjustadaParaCalculo...,RECEITA CORRENTE LÍQUIDA AJUSTADA PARA CÁLCULO...,1.298524e+10
219,2021,RREO,6,B,Governo do Estado de São Paulo,35,SP,46289333,RREO-Anexo 03,E,Padrão,<MR-2>,RREO3CotaParteDoFPE,Cota-Parte do FPE,9.067024e+07

In [19]:
drop = rreo_df.columns[1:11]
rreo_df = rreo_df.drop(columns=drop)

In [ ]:
#rreo_df["cod_conta"].unique()

array(['ReceitasExcetoIntraOrcamentarias', 'ReceitasCorrentes',
       'ReceitaTributaria', 'Impostos', 'Taxas', 'ContribuicaoDeMelhoria',
       'ReceitaDeContribuicoes', 'ContribuicoesSociais',
       'ReceitaPatrimonial', 'ReceitasImobiliarias',
       'ReceitasDeValoresMobiliarios', 'ReceitaDeConcessoesEPermissoes',
       'ExploracaoDeRecursosNaturais', 'ExploracaoDoPatrimonioIntangivel',
       'ReceitaDaCessaoDeDireitos', 'ReceitaAgropecuaria',
       'ReceitaIndustrial', 'ReceitaDeServicos',
       'ServicosAdministrativosEComerciaisGerais',
       'ServicosEAtividadesReferentesANavegacaoEAoTransporte',
       'ServicosEAtividadesReferentesASaude',
       'ServicosEAtividadesFinanceiras', 'OutrosServicos',
       'TransferenciasCorrentes',
       'TransferenciasCorrentesDaUniaoEDeSuasEntidades',
       'TransferenciasCorrentesDosEstadosEDoDistritoFederalEDeSuasEntidades',
       'TransferenciasCorrentesDosMunicipiosEDeSuasEntidades',
       'TransferenciasCorrentesDeInstituicoesPrivadas',
       'TransferenciasCorrentesDeOutrasInstituicoesPublicas',
       'TransferenciasCorrentesDoExterior',
       'TransferenciasCorrentesDePessoasFisicas',
       'OutrasReceitasCorrentes', 'MultasEJurosDeMora',
       'IndenizacoesERestituicoes', 'ReceitasCorrentesDiversas',
       'ReceitasDeCapital', 'ReceitasDeOperacoesDeCredito',
       'OperacoesDeCreditoInternas', 'OperacoesDeCreditoExternas',
       'AlienacaoDeBens', 'AlienacaoDeBensMoveis',
       'AlienacaoDeBensImoveis', 'AlienacaoDeBensIntangiveis',
       'AmortizacoesDeEmprestimos', 'TransferenciasDeCapital',
       'TransferenciasDeCapitalDaUniaoEDeSuasEntidades',
       'TransferenciasDeCapitalDosEstadosEDoDistritoFederalEDeSuasEntidades',
       'TransferenciasdeCapitalDosMunicipiosEDeSuasEntidades',
       'TransferenciasDeCapitalDeInstituicoesPrivadas',
       'TransferenciasDeCapitalDeOutrasInstituicoesPublicas',
       'TransferenciasDeCapitalDoExterior', 'OutrasReceitasDeCapital',
       'RREO1OutrasReceitasDeCapital', 'ReceitasIntraOrcamentariasTotal',
       'SubtotalDasReceitas', 'TotalReceitas', 'TotalReceitasComDeficit',
       'SaldoDeExerciciosAnterioresUtilizadosParaCreditosAdicionais',
       'SuperavitFinanceiro', 'DespesasExcetoIntraOrcamentarias',
       'DespesasCorrentes', 'PessoalEEncargosSociais',
       'JurosEEncargosDaDivida', 'OutrasDespesasCorrentes',
       'TransferenciasAMunicipios', 'DemaisDespesasCorrentes',
       'DespesasDeCapital', 'Investimentos', 'InversoesFinanceiras',
       'AmortizacaoDaDivida', 'ReservaDeContingencia',
       'DespesasIntraOrcamentariasTotal', 'SubtotalDasDespesas',
       'TotalDespesas', 'Superavit', 'TotalDespesasComSuperavit',
       'ReceitasIntraOrcamentarias', 'ReceitasCorrentesIntra',
       'ReceitaDeContribuicoesIntra', 'ContribuicoesSociaisIntra',
       'ReceitaAgropecuariaIntra', 'ReceitaDeServicosIntra',
       'ServicosAdministrativosEComerciaisGeraisIntra',
       'ServicosEAtividadesReferentesASaudeIntra', 'OutrosServicosIntra',
       'TransferenciasCorrentesIntra',
       'TransferenciasCorrentesDosEstadosEDoDistritoFederalEDeSuasEntidadesIntra',
       'OutrasReceitasCorrentesIntra', 'IndenizacoesERestituicoesIntra',
       'ReceitasDeCapitalIntra', 'AlienacaoDeBensIntra',
       'AlienacaoDeBensImoveisIntra', 'OutrasReceitasDeCapitalIntra',
       'IntegralizacaoDoCapitalSocialIntra',
       'RREO1OutrasReceitasDeCapitalIntra', 'DespesasIntraOrcamentarias',
       'DespesasCorrentesIntra', 'PessoalEEncargosSociaisIntra',
       'JurosEEncargosDaDividaIntra', 'OutrasDespesasCorrentesIntra',
       'DespesasDeCapitalIntra', 'InvestimentosIntra',
       'InversoesFinanceirasIntra', 'AmortizacaoDaDividaIntra',
       'ReceitasCorrentesLiquidasExcetoTransferenciasEFUNDEB',
       'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB',
       'ICMSLiquidoExcetoTransferenciasEFUNDEB',
       'IPVALiquidoExcetoTransferenciasEFUNDEB',
       'ITCDLiquidoExcetoTransferenciasEFUNDEB',
       'IRRFLiquidoExcetoTransferenciasEFUNDEB',
       'OutrasReceitasTributarias', 'RREO3ReceitaDeContribuicoes',
       'RREO3ReceitaPatrimonial', 'RendimentosDeAplicacaoFinanceira',
       'OutrasReceitasPatrimoniais', 'RREO3ReceitaAgropecuaria',
       'RREO3ReceitaIndustrial', 'RREO3ReceitaDeServicos',
       'RREO3TransferenciasCorrentes', 'RREO3CotaParteDoFPE',
       'RREO3TransferenciasDaLC871996', 'RREO3TransferenciasDaLC611989',
       'RREO3OutrasTransferenciasCorrentes',
       'RREO3OutrasReceitasCorrentes', 'DeducoesDaReceitaCorrenteLiquida',
       'ReceitaDeTransferenciasConstitucionaisELegais',
       'ContribuicaoDoServidorParaOPlanoDePrevidencia',
       'CompensacaoFinanceiraEntreRegimesPrevidencia',
       'DeducaoDeReceitaParaFormacaoDoFUNDEB',
       'RREO3ReceitaCorrenteLiquida',
       'RREO3TransferenciasObrigatoriasDaUniaoRelativasAsEmendasIndividuais',
       'RREO3ReceitaCorrenteLiquidaAjustadaParaCalculoDosLimitesDeEndividamento',
       'RREO3TransferenciasObrigatoriasDaUniaoRelativasAsEmendasDeBancada',
       'RREO3ReceitaCorrenteLiquidaAjustadaParaCalculoDosLimitesDaDespesaComPessoal',
       'OutrasTransferenciasCorrentes', 'Deficit',
       'TransferenciasCorrentesDaUniaoEDeSuasEntidadesIntra',
       'RendimentosDeAplicacoesDeRecursosPrevidenciarios',
       'RREO3TransferenciasDoFUNDEB'], dtype=object)

In [20]:
rreo_df['coluna'] = np.where(rreo_df['coluna'].str.contains('PREVISÃO ATUALIZADA'), 'PREVISÃO ATUALIZADA', rreo_df['coluna'])

In [21]:
rreo_df_pivot = rreo_df.pivot_table(index=['exercicio','cod_conta'], columns='coluna', values='valor', aggfunc='sum')

In [25]:
rreo_df_pivot.fillna(0, inplace=True)

In [43]:
rreo_df_pivot.sample(5)

coluna                                                        % (b/a)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades        21.52
2020      InversoesFinanceiras                                   0.00
          SuperavitFinanceiro                                    0.00
2023      AmortizacaoRefinanciamentoDaDivida                     0.00
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...     0.00

coluna                                                        % (c/a)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades       117.18
2020      InversoesFinanceiras                                   0.00
          SuperavitFinanceiro                                    0.00
2023      AmortizacaoRefinanciamentoDaDivida                     0.00
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...     0.00

coluna                                                        <MR-10>  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades          0.0
2020      InversoesFinanceiras                                    0.0
          SuperavitFinanceiro                                     0.0
2023      AmortizacaoRefinanciamentoDaDivida                      0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...      0.0

coluna                                                        <MR-11>  <MR-1>  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades          0.0     0.0
2020      InversoesFinanceiras                                    0.0     0.0
          SuperavitFinanceiro                                     0.0     0.0
2023      AmortizacaoRefinanciamentoDaDivida                      0.0     0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...      0.0     0.0

coluna                                                           <MR-2>  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades            0.0
2020      InversoesFinanceiras                                      0.0
          SuperavitFinanceiro                                       0.0
2023      AmortizacaoRefinanciamentoDaDivida                        0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...  1000000.0

coluna                                                        <MR-3>  <MR-4>  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades         0.0     0.0
2020      InversoesFinanceiras                                   0.0     0.0
          SuperavitFinanceiro                                    0.0     0.0
2023      AmortizacaoRefinanciamentoDaDivida                     0.0     0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...     0.0     0.0

coluna                                                        <MR-5>  <MR-6>  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades         0.0     0.0
2020      InversoesFinanceiras                                   0.0     0.0
          SuperavitFinanceiro                                    0.0     0.0
2023      AmortizacaoRefinanciamentoDaDivida                     0.0     0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...     0.0     0.0

coluna                                                        ...  \
exercicio cod_conta                                           ...
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades      ...
2020      InversoesFinanceiras                                ...
          SuperavitFinanceiro                                 ...
2023      AmortizacaoRefinanciamentoDaDivida                  ...
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...  ...

coluna                                                        DOTAÇÃO ATUALIZADA (e)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades                        0.00
2020      InversoesFinanceiras                                           19193071.35
          SuperavitFinanceiro                                                   0.00
2023      AmortizacaoRefinanciamentoDaDivida                             86019721.06
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...                    0.00

coluna                                                        DOTAÇÃO INICIAL (d)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades                      0.0
2020      InversoesFinanceiras                                         11142480.0
          SuperavitFinanceiro                                                 0.0
2023      AmortizacaoRefinanciamentoDaDivida                           65297797.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...                  0.0

coluna                                                        INSCRITAS EM RESTOS A PAGAR NÃO PROCESSADOS (k)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades                                                  0.0
2020      InversoesFinanceiras                                                                            0.0
          SuperavitFinanceiro                                                                             0.0
2023      AmortizacaoRefinanciamentoDaDivida                                                              0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...                                              0.0

coluna                                                        No Bimestre (b)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades         7.561027e+08
2020      InversoesFinanceiras                                   0.000000e+00
          SuperavitFinanceiro                                    0.000000e+00
2023      AmortizacaoRefinanciamentoDaDivida                     0.000000e+00
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...     0.000000e+00

coluna                                                        PREVISÃO ATUALIZADA  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades             3.513904e+09
2020      InversoesFinanceiras                                       0.000000e+00
          SuperavitFinanceiro                                        8.690597e+08
2023      AmortizacaoRefinanciamentoDaDivida                         0.000000e+00
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...         0.000000e+00

coluna                                                        PREVISÃO INICIAL  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades          3.139558e+09
2020      InversoesFinanceiras                                    0.000000e+00
          SuperavitFinanceiro                                     0.000000e+00
2023      AmortizacaoRefinanciamentoDaDivida                      0.000000e+00
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...      0.000000e+00

coluna                                                         SALDO (a-c)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades     -6.036450e+08
2020      InversoesFinanceiras                                0.000000e+00
          SuperavitFinanceiro                                 0.000000e+00
2023      AmortizacaoRefinanciamentoDaDivida                  0.000000e+00
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...  0.000000e+00

coluna                                                        SALDO (g) = (e-f)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades                   0.00
2020      InversoesFinanceiras                                       8001571.38
          SuperavitFinanceiro                                              0.00
2023      AmortizacaoRefinanciamentoDaDivida                        20126035.44
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...               0.00

coluna                                                        SALDO (i) = (e-h)  \
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades                   0.00
2020      InversoesFinanceiras                                       8001571.38
          SuperavitFinanceiro                                              0.00
2023      AmortizacaoRefinanciamentoDaDivida                        20126035.44
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...               0.00

coluna                                                        TOTAL (ÚLTIMOS 12 MESES)
exercicio cod_conta
2022      TransferenciasCorrentesDaUniaoEDeSuasEntidades                           0.0
2020      InversoesFinanceiras                                                     0.0
          SuperavitFinanceiro                                                      0.0
2023      AmortizacaoRefinanciamentoDaDivida                                       0.0
2021      RREO3TransferenciasObrigatoriasDaUniaoRelativas...                 1000000.0

[5 rows x 30 columns]

In [46]:
rreo_df_pivot.loc[2023]
#.get('Até o Bimestre (c)', 0) / 1_000_000_000, 2),

coluna,% (b/a),% (c/a),<MR-10>,<MR-11>,<MR-1>,<MR-2>,<MR-3>,<MR-4>,<MR-5>,<MR-6>,...,DOTAÇÃO ATUALIZADA (e),DOTAÇÃO INICIAL (d),INSCRITAS EM RESTOS A PAGAR NÃO PROCESSADOS (k),No Bimestre (b),PREVISÃO ATUALIZADA,PREVISÃO INICIAL,SALDO (a-c),SALDO (g) = (e-f),SALDO (i) = (e-h),TOTAL (ÚLTIMOS 12 MESES)
cod_conta,,,,,,,,,,,,,,,,,,,,,
AlienacaoDeBens,285.01,957.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2571192.24,902150.0,902150.0,-7738164.20,0.0,0.0,0.0
AlienacaoDeBensImoveis,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,57830.24,0.0,0.0,-4228151.20,0.0,0.0,0.0
AlienacaoDeBensImoveisIntra,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,-33821.25,0.0,0.0,0.0
AlienacaoDeBensIntra,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,-33821.25,0.0,0.0,0.0
AlienacaoDeBensMoveis,278.60,489.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2513362.00,902150.0,902150.0,-3510013.00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TransferenciasCorrentesDosEstadosEDoDistritoFederalEDeSuasEntidades,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,1029838.0,1029838.0,1029838.00,0.0,0.0,0.0
TransferenciasCorrentesDosMunicipiosEDeSuasEntidades,44.96,168.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1570930.38,3493800.0,3493800.0,-2379533.07,0.0,0.0,0.0
TransferenciasDeCapital,16.35,68.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,29537950.77,180653021.7,118717257.0,57516276.33,0.0,0.0,0.0
TransferenciasDeCapitalDaUniaoEDeSuasEntidades,16.38,68.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,29537006.51,180293021.7,118357257.0,57209593.88,0.0,0.0,0.0
TransferenciasDeCapitalDeInstituicoesPrivadas,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,360000.0,360000.0,360000.00,0.0,0.0,0.0

In [ ]:
def get_value(exercicio, conta, coluna):
    try:
        return round(rreo_df_pivot.loc[(exercicio, conta), coluna] / 1_000_000_000, 2)
    except KeyError:
        return 0  # Retorna 0 caso a conta ou a coluna não existam


df_teste = {'RECEITAS':['RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)',
                         'IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA',
                         'CONTRIBUIÇÕES',
                         'RECEITA PATRIMONIAL',
                         'RECEITA AGROPECUÁRIA',
                         'RECEITA INDUSTRIAL',
                         'RECEITA DE SERVIÇOS',
                         'TRANSFERÊNCIAS CORRENTES',
                         'OUTRAS RECEITAS CORRENTES'                        
                         ],
            'PREVISÃO ATUALIZADA (A)':[
                        0,
                        get_value(2024, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'ReceitaDeContribuicoes', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'ReceitaPatrimonial', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'ReceitaAgropecuaria', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'ReceitaIndustrial', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'ReceitaDeServicos', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'RREO3TransferenciasCorrentes', 'PREVISÃO ATUALIZADA'),
                        get_value(2024, 'OutrasReceitasCorrentes', 'PREVISÃO ATUALIZADA')
                        ],
            'ARRECADADO (B)': [
                        0,
                        get_value(2024, 'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB', 'TOTAL (ÚLTIMOS 12 MESES)'),
                        get_value(2024, 'ReceitaDeContribuicoes', 'Até o Bimestre (c)'),
                        get_value(2024, 'ReceitaPatrimonial', 'Até o Bimestre (c)'),
                        get_value(2024, 'ReceitaAgropecuaria', 'Até o Bimestre (c)'),
                        get_value(2024, 'ReceitaIndustrial', 'Até o Bimestre (c)'),
                        get_value(2024, 'ReceitaDeServicos', 'Até o Bimestre (c)'),
                        get_value(2024, 'RREO3TransferenciasCorrentes', 'TOTAL (ÚLTIMOS 12 MESES)'),
                        get_value(2024, 'OutrasReceitasCorrentes', 'Até o Bimestre (c)')                       
                        ]
            '% (C=B/A)' : [
                        0,
                        ]
                        }

df_teste = pd.DataFrame(df_teste)

df_teste.loc[df_teste['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', 'PREVISÃO ATUALIZADA'] = df_teste.loc[1:, 'PREVISÃO ATUALIZADA'].sum()
df_teste.loc[df_teste['RECEITAS'] == 'RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS)', 'ARRECADADO'] = df_teste.loc[1:, 'ARRECADADO'].sum()


df_teste

,RECEITAS,PREVISÃO ATUALIZADA,ARRECADADO
0,RECEITAS CORRENTES (EXCETO INTRA-ORÇAMENTÁRIAS),19.45,19.38
1,"IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA",9.52,9.34
2,CONTRIBUIÇÕES,0.53,0.62
3,RECEITA PATRIMONIAL,0.83,0.65
4,RECEITA AGROPECUÁRIA,0.00,0.00
5,RECEITA INDUSTRIAL,0.00,0.00
6,RECEITA DE SERVIÇOS,0.44,0.49
7,TRANSFERÊNCIAS CORRENTES,7.68,7.70
8,OUTRAS RECEITAS CORRENTES,0.45,0.58

In [36]:
rreo_df['cod_conta'].unique()

array(['ReceitasExcetoIntraOrcamentarias', 'ReceitasCorrentes',
       'ReceitaTributaria', 'Impostos', 'Taxas', 'ContribuicaoDeMelhoria',
       'ReceitaDeContribuicoes', 'ContribuicoesSociais',
       'ReceitaPatrimonial', 'ReceitasImobiliarias',
       'ReceitasDeValoresMobiliarios', 'ReceitaDeConcessoesEPermissoes',
       'ExploracaoDeRecursosNaturais', 'ExploracaoDoPatrimonioIntangivel',
       'ReceitaDaCessaoDeDireitos', 'ReceitaAgropecuaria',
       'ReceitaIndustrial', 'ReceitaDeServicos',
       'ServicosAdministrativosEComerciaisGerais',
       'ServicosEAtividadesReferentesANavegacaoEAoTransporte',
       'ServicosEAtividadesReferentesASaude',
       'ServicosEAtividadesFinanceiras', 'OutrosServicos',
       'TransferenciasCorrentes',
       'TransferenciasCorrentesDaUniaoEDeSuasEntidades',
       'TransferenciasCorrentesDosEstadosEDoDistritoFederalEDeSuasEntidades',
       'TransferenciasCorrentesDosMunicipiosEDeSuasEntidades',
       'TransferenciasCorrentesDeInstituicoesPrivadas',
       'TransferenciasCorrentesDeOutrasInstituicoesPublicas',
       'TransferenciasCorrentesDoExterior',
       'TransferenciasCorrentesDePessoasFisicas',
       'OutrasReceitasCorrentes', 'MultasEJurosDeMora',
       'IndenizacoesERestituicoes', 'ReceitasCorrentesDiversas',
       'ReceitasDeCapital', 'ReceitasDeOperacoesDeCredito',
       'OperacoesDeCreditoInternas', 'OperacoesDeCreditoExternas',
       'AlienacaoDeBens', 'AlienacaoDeBensMoveis',
       'AlienacaoDeBensImoveis', 'AlienacaoDeBensIntangiveis',
       'AmortizacoesDeEmprestimos', 'TransferenciasDeCapital',
       'TransferenciasDeCapitalDaUniaoEDeSuasEntidades',
       'TransferenciasDeCapitalDosEstadosEDoDistritoFederalEDeSuasEntidades',
       'TransferenciasdeCapitalDosMunicipiosEDeSuasEntidades',
       'TransferenciasDeCapitalDeInstituicoesPrivadas',
       'TransferenciasDeCapitalDeOutrasInstituicoesPublicas',
       'TransferenciasDeCapitalDoExterior', 'OutrasReceitasDeCapital',
       'RREO1OutrasReceitasDeCapital', 'ReceitasIntraOrcamentariasTotal',
       'SubtotalDasReceitas', 'TotalReceitas', 'TotalReceitasComDeficit',
       'SaldoDeExerciciosAnterioresUtilizadosParaCreditosAdicionais',
       'SuperavitFinanceiro', 'DespesasExcetoIntraOrcamentarias',
       'DespesasCorrentes', 'PessoalEEncargosSociais',
       'JurosEEncargosDaDivida', 'OutrasDespesasCorrentes',
       'TransferenciasAMunicipios', 'DemaisDespesasCorrentes',
       'DespesasDeCapital', 'Investimentos', 'InversoesFinanceiras',
       'AmortizacaoDaDivida', 'ReservaDeContingencia',
       'DespesasIntraOrcamentariasTotal', 'SubtotalDasDespesas',
       'TotalDespesas', 'Superavit', 'TotalDespesasComSuperavit',
       'ReceitasIntraOrcamentarias', 'ReceitasCorrentesIntra',
       'ReceitaDeContribuicoesIntra', 'ContribuicoesSociaisIntra',
       'ReceitaAgropecuariaIntra', 'ReceitaDeServicosIntra',
       'ServicosAdministrativosEComerciaisGeraisIntra',
       'ServicosEAtividadesReferentesASaudeIntra', 'OutrosServicosIntra',
       'TransferenciasCorrentesIntra',
       'TransferenciasCorrentesDosEstadosEDoDistritoFederalEDeSuasEntidadesIntra',
       'OutrasReceitasCorrentesIntra', 'IndenizacoesERestituicoesIntra',
       'ReceitasDeCapitalIntra', 'AlienacaoDeBensIntra',
       'AlienacaoDeBensImoveisIntra', 'OutrasReceitasDeCapitalIntra',
       'IntegralizacaoDoCapitalSocialIntra',
       'RREO1OutrasReceitasDeCapitalIntra', 'DespesasIntraOrcamentarias',
       'DespesasCorrentesIntra', 'PessoalEEncargosSociaisIntra',
       'JurosEEncargosDaDividaIntra', 'OutrasDespesasCorrentesIntra',
       'DespesasDeCapitalIntra', 'InvestimentosIntra',
       'InversoesFinanceirasIntra', 'AmortizacaoDaDividaIntra',
       'ReceitasCorrentesLiquidasExcetoTransferenciasEFUNDEB',
       'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB',
       'ICMSLiquidoExcetoTransferenciasEFUNDEB',
       'IPVALiquidoExcetoTransferenciasEFUNDEB',
       'ITCDLiquidoExcetoTransferenciasEFUNDEB',
       'IRRFLiquidoExcetoTransferenciasEFUNDEB',
       'OutrasReceitasTributarias', 'RREO3ReceitaDeContribuicoes',
       'RREO3ReceitaPatrimonial', 'RendimentosDeAplicacaoFinanceira',
       'OutrasReceitasPatrimoniais', 'RREO3ReceitaAgropecuaria',
       'RREO3ReceitaIndustrial', 'RREO3ReceitaDeServicos',
       'RREO3TransferenciasCorrentes', 'RREO3CotaParteDoFPE',
       'RREO3TransferenciasDaLC871996', 'RREO3TransferenciasDaLC611989',
       'RREO3OutrasTransferenciasCorrentes',
       'RREO3OutrasReceitasCorrentes', 'DeducoesDaReceitaCorrenteLiquida',
       'ReceitaDeTransferenciasConstitucionaisELegais',
       'ContribuicaoDoServidorParaOPlanoDePrevidencia',
       'CompensacaoFinanceiraEntreRegimesPrevidencia',
       'DeducaoDeReceitaParaFormacaoDoFUNDEB',
       'RREO3ReceitaCorrenteLiquida',
       'RREO3TransferenciasObrigatoriasDaUniaoRelativasAsEmendasIndividuais',
       'RREO3ReceitaCorrenteLiquidaAjustadaParaCalculoDosLimitesDeEndividamento',
       'RREO3TransferenciasObrigatoriasDaUniaoRelativasAsEmendasDeBancada',
       'RREO3ReceitaCorrenteLiquidaAjustadaParaCalculoDosLimitesDaDespesaComPessoal',
       'OutrasTransferenciasCorrentes', 'Deficit',
       'TransferenciasCorrentesDaUniaoEDeSuasEntidadesIntra',
       'RendimentosDeAplicacoesDeRecursosPrevidenciarios',
       'RREO3TransferenciasDoFUNDEB'], dtype=object)

In [ ]:
#rreo_df[(rreo_df['exercicio'] == 2024) & (rreo_df['anexo'] == 'RREO-Anexo 01')].pivot_table(index=['exercicio','cod_conta','conta'], columns=['coluna'], values='valor', aggfunc='sum').to_excel('rreo.xlsx')

In [14]:
contas_receitas_correntes = [
    'ReceitaDeContribuicoes',
    'ReceitaPatrimonial',
    'ReceitaDeServicos',
    'OutrasReceitasCorrentes',
    'ReceitasIntraOrcamentariasTotal',
    'RREO3TransferenciasCorrentes',
    'ReceitaTributariaLiquidaExcetoTransferenciasEFUNDEB',
]

contas_receitas_capital = [
    'ReceitasDeOperacoesDeCredito',
    'AlienacaoDeBens',
    'AmortizacoesDeEmprestimos',
    'TransferenciasDeCapital',
    'OutrasReceitasDeCapital'
    
]

filtro_receitas_correntes = rreo_df[rreo_df['cod_conta'].isin(contas_receitas_correntes)]
filtro_receitas_capital = rreo_df[rreo_df['cod_conta'].isin(contas_receitas_capital)]


# Agrupando por 'exercicio' e somando os valores
receitas_correntes_anexo01 = filtro_receitas_correntes.query("coluna == 'Até o Bimestre (c)'").groupby(['exercicio','conta'])['valor'].sum().reset_index()
receitas_correntes_anexo03 = filtro_receitas_correntes.query("coluna == 'TOTAL (ÚLTIMOS 12 MESES)'").groupby(['exercicio','conta'])['valor'].sum().reset_index()

receitas_capital = filtro_receitas_capital.query("coluna == 'Até o Bimestre (c)'").groupby(['exercicio','conta'])['valor'].sum().reset_index()

receitas_brutas = pd.concat([receitas_correntes_anexo01, receitas_correntes_anexo03, receitas_capital]).groupby(['exercicio'])['valor'].sum().reset_index()

receitas_brutas['valor_bilhoes'] = (receitas_brutas['valor'] / 1000000000).round(2)

receitas_brutas

   exercicio         valor  valor_bilhoes
0       2020  1.208867e+10          12.09
1       2021  1.415043e+10          14.15
2       2022  1.678566e+10          16.79
3       2023  1.794761e+10          17.95
4       2024  2.063299e+10          20.63

In [15]:
import matplotlib.pyplot as plt
import seaborn as sns

# Configuração do estilo do gráfico
sns.set_style()  # Fundo mais limpo
plt.figure(figsize=(12, 5))  # Ajustando o tamanho

# Criando o gráfico de barras
cores = sns.color_palette("Set2", len(receitas_correntes))  # Paleta de cores
plt.bar(receitas_correntes['exercicio'], receitas_correntes['valor_bilhoes'], color=cores)

# Adicionando rótulos e título
plt.xlabel("Exercício", fontsize=12)
plt.ylabel("Valor (Bilhões)", fontsize=12)
plt.title("Receita Bruta Arrecadada (em Bilhões)", fontsize=14, fontweight="bold")

# Ajustando os rótulos do eixo X
plt.xticks(receitas_correntes['exercicio'], rotation=45)

# Adicionando rótulos nas barras
for i, valor in enumerate(receitas_correntes['valor_bilhoes']):
    plt.text(receitas_correntes['exercicio'][i], valor + 0.05, f"{valor:.2f}", 
             ha='center', fontsize=10, fontweight='bold', color='black')

# Exibindo o gráfico
plt.show()

NameError: name 'receitas_correntes' is not defined

In [70]:
rreo_df.query("valor > 1000000000")[['coluna','conta','valor']].head(2)

,coluna,conta,valor
0,PREVISÃO INICIAL,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),7.862012e+09
1,PREVISÃO ATUALIZADA (a),RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),8.138927e+09

In [72]:
rreo_df.query("conta == 'OUTRAS RECEITAS DE CAPITAL'")[['coluna','conta','valor']].head(2)

                 coluna                       conta       valor
444     No Bimestre (b)  OUTRAS RECEITAS DE CAPITAL  2155433.65
445  Até o Bimestre (c)  OUTRAS RECEITAS DE CAPITAL  3416333.65

In [55]:
data = rreo_df.pivot_table(index=['exercicio','conta'], columns='coluna', values='valor', aggfunc='sum')

data.head(3)

coluna                              % (b/a)  % (c/a)  Até o Bimestre (c)  \
exercicio conta
2019      ALIENAÇÃO DE BENS          226.13   344.55           1264826.6
          AMORTIZAÇÃO DA DÍVIDA         NaN      NaN                 NaN
          Alienação de Bens Móveis   226.13   344.55           1264826.6

coluna                              DESPESAS EMPENHADAS ATÉ O BIMESTRE (f)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                                            NaN
          AMORTIZAÇÃO DA DÍVIDA                               1.918664e+08
          Alienação de Bens Móveis                                     NaN

coluna                              DESPESAS EMPENHADAS NO BIMESTRE  \
exercicio conta
2019      ALIENAÇÃO DE BENS                                     NaN
          AMORTIZAÇÃO DA DÍVIDA                         38923054.28
          Alienação de Bens Móveis                              NaN

coluna                              DESPESAS LIQUIDADAS ATÉ O BIMESTRE (h)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                                            NaN
          AMORTIZAÇÃO DA DÍVIDA                               1.918664e+08
          Alienação de Bens Móveis                                     NaN

coluna                              DESPESAS LIQUIDADAS NO BIMESTRE  \
exercicio conta
2019      ALIENAÇÃO DE BENS                                     NaN
          AMORTIZAÇÃO DA DÍVIDA                         38994871.18
          Alienação de Bens Móveis                              NaN

coluna                              DESPESAS PAGAS ATÉ O BIMESTRE (j)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                                       NaN
          AMORTIZAÇÃO DA DÍVIDA                          1.918664e+08
          Alienação de Bens Móveis                                NaN

coluna                              DOTAÇÃO ATUALIZADA (e)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                            NaN
          AMORTIZAÇÃO DA DÍVIDA                191967244.2
          Alienação de Bens Móveis                     NaN

coluna                              DOTAÇÃO INICIAL (d)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                         NaN
          AMORTIZAÇÃO DA DÍVIDA             139215197.0
          Alienação de Bens Móveis                  NaN

coluna                              INSCRITAS EM RESTOS A PAGAR NÃO PROCESSADOS (k)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                                                     NaN
          AMORTIZAÇÃO DA DÍVIDA                                                 NaN
          Alienação de Bens Móveis                                              NaN

coluna                              No Bimestre (b)  PREVISÃO ATUALIZADA (a)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                830126.6                 367100.0
          AMORTIZAÇÃO DA DÍVIDA                 NaN                      NaN
          Alienação de Bens Móveis         830126.6                 367100.0

coluna                              PREVISÃO INICIAL  SALDO (a-c)  \
exercicio conta
2019      ALIENAÇÃO DE BENS                      NaN    -897726.6
          AMORTIZAÇÃO DA DÍVIDA                  NaN          NaN
          Alienação de Bens Móveis               NaN    -897726.6

coluna                              SALDO (g) = (e-f)  SALDO (i) = (e-h)
exercicio conta
2019      ALIENAÇÃO DE BENS                       NaN                NaN
          AMORTIZAÇÃO DA DÍVIDA             100892.59          100892.59
          Alienação de Bens Móveis                NaN                NaN

In [53]:
soma = filtered_data.loc["Alienação de Bens Móveis"].sum()
soma

KeyError: 'Alienação de Bens Móveis'

In [47]:
pip install docx

Collecting docxNote: you may need to restart the kernel to use updated packages.

  Downloading docx-0.2.4.tar.gz (54 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting lxml (from docx)
  Using cached lxml-5.3.1-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Collecting Pillow>=2.0 (from docx)
  Downloading pillow-11.1.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Downloading pillow-11.1.0-cp311-cp311-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.6 MB 1.0 MB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.6 MB 1.0 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.6 MB 1.1 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.6 MB 1.1 MB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.6 MB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.6 MB 1.1 MB/s eta 0:00:01
   ------------------------------- -------- 2.1/2.6 MB 1.2 MB/s eta 0:00:01
   ----------------------------------- ---- 2.4/2.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 1.1 MB/s eta 0:00:00
Using cached lxml-5.3.1-cp311-cp311-win_amd64.whl (3.8 MB)
Building wheels for collected packages: docx
  Building wheel for docx (pyproject.toml): started
  Building wheel for docx (pyproject.toml): finished with status 'done'
  Created wheel for docx: filename=docx-0.2.4-py3-none-any.whl size=53940 sha256=f9cc044f867d3aa0b5ef028efbbd6929aedab92e0f3d0e90e78b130890d7a26e
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\c1\3e\c3\e81c11effd0be5658a035947c66792dd993bcff317eae0e1ed
Successfully built docx
Installing collected packages: Pillow, lxml, docx
Successfully installed Pillow-11.1.0 docx-0.2.4 lxml-5.3.1

In [50]:
import docx

doc = docx.Document()

# Add title (heading level 0)
doc.add_heading('Relatorio teste', level=0)

p = doc.add_paragraph(
    f"No exercício de {exercicio}, a receita arrecadada no bimestre foi de R$ {soma_no_bimestre_2024:,.2f} bilhões, "
)

ModuleNotFoundError: No module named 'exceptions'

In [138]:
rreo_df['coluna'] = np.where(rreo_df['coluna'].str.contains('PREVISÃO ATUALIZADA', na=False), 'PREVISÃO ATUALIZADA', rreo_df['coluna'])

In [139]:
rreo_df['coluna'].unique()

array(['<MR-11>', '<MR-10>', '<MR-9>', '<MR-8>', '<MR-7>', '<MR-6>',
       '<MR-5>', '<MR-4>', '<MR-3>', '<MR-2>', '<MR-1>', '<MR>',
       'TOTAL (ÚLTIMOS 12 MESES)', 'PREVISÃO ATUALIZADA'], dtype=object)

In [140]:
receitas_correntes_anexo_03 = [
    'Transferências Correntes',
    'Impostos, Taxas e Contribuições de Melhoria',
]

rc_03 = rreo_df[(rreo_df['conta'].isin(receitas_correntes_anexo_03))& rreo_df['coluna'].isin(['TOTAL (ÚLTIMOS 12 MESES)','PREVISÃO ATUALIZADA'])]

In [141]:
rc_03.pivot_table(index=['exercicio','conta'], columns='coluna', values='valor_bilhoes', aggfunc='sum')

coluna                                                 PREVISÃO ATUALIZADA  \
exercicio conta
2019      Impostos, Taxas e Contribuições de Melhoria                 4.84
          Transferências Correntes                                    4.13
2020      Impostos, Taxas e Contribuições de Melhoria                 4.80
          Transferências Correntes                                    5.02
2021      Impostos, Taxas e Contribuições de Melhoria                 5.61
          Transferências Correntes                                    4.84
2022      Impostos, Taxas e Contribuições de Melhoria                 7.22
          Transferências Correntes                                    5.60
2024      Impostos, Taxas e Contribuições de Melhoria                 9.52
          Transferências Correntes                                    7.68

coluna                                                 TOTAL (ÚLTIMOS 12 MESES)
exercicio conta
2019      Impostos, Taxas e Contribuições de Melhoria                      5.00
          Transferências Correntes                                         4.24
2020      Impostos, Taxas e Contribuições de Melhoria                      5.38
          Transferências Correntes                                         4.92
2021      Impostos, Taxas e Contribuições de Melhoria                      6.91
          Transferências Correntes                                         5.37
2022      Impostos, Taxas e Contribuições de Melhoria                      7.37
          Transferências Correntes                                         6.38
2024      Impostos, Taxas e Contribuições de Melhoria                      9.34
          Transferências Correntes                                         7.70

In [142]:
an_exercicio = ['2019','2020','2021','2022','2024']
id_ente = "11" #Código IBGE do Ente.

rreo_df = pd.DataFrame()
co_tipo_demonstrativo = 'RREO' #tipo de demonstrativo RREO - Bimestre
nr_periodo = '6' #periodo RREO - Bimestre
no_anexo = 'RREO-Anexo 01'

for i in an_exercicio:
    dados = RREO(i, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente)
    df = dados['items']
    df = pd.DataFrame(df)
    rreo_df = pd.concat([rreo_df, df], ignore_index=True)
    rreo_df['valor_bilhoes'] = (rreo_df['valor'] / 1000000000).round(2)

In [143]:
receitas_correntes_anexo_01 = [
    'ReceitaDeContribuicoes',
    'ReceitaPatrimonial',
    'ReceitaDeServicos',
    'OutrasReceitasCorrentes',
    'ReceitasIntraOrcamentariasTotal'
]

rc_01 = rreo_df[ (rreo_df['cod_conta'].isin(receitas_correntes_anexo_01))
                 & (rreo_df['coluna'].isin(['Até o Bimestre (c)']))]

In [144]:
rc_01.pivot_table(index=['exercicio','conta'], columns='coluna', values='valor_bilhoes', aggfunc='sum')

coluna                                         Até o Bimestre (c)
exercicio conta
2019      CONTRIBUIÇÕES                                      0.36
          OUTRAS RECEITAS CORRENTES                          0.27
          RECEITA DE SERVIÇOS                                0.28
          RECEITA PATRIMONIAL                                0.36
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.35
2020      CONTRIBUIÇÕES                                      0.36
          OUTRAS RECEITAS CORRENTES                          0.26
          RECEITA DE SERVIÇOS                                0.28
          RECEITA PATRIMONIAL                                0.40
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.43
2021      CONTRIBUIÇÕES                                      0.38
          OUTRAS RECEITAS CORRENTES                          0.31
          RECEITA DE SERVIÇOS                                0.35
          RECEITA PATRIMONIAL                                0.36
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.36
2022      CONTRIBUIÇÕES                                      0.49
          OUTRAS RECEITAS CORRENTES                          0.41
          RECEITA DE SERVIÇOS                                0.42
          RECEITA PATRIMONIAL                                0.88
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                0.71
2024      CONTRIBUIÇÕES                                      0.62
          OUTRAS RECEITAS CORRENTES                          0.58
          RECEITA DE SERVIÇOS                                0.49
          RECEITA PATRIMONIAL                                0.65
          RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)                1.12

In [150]:
total_rc_01 = rc_01[(rc_01['coluna'] == 'Até o Bimestre (c)')&(rc_01['exercicio'] == 2024)]['valor_bilhoes'].sum()
total_rc_03 = rc_03[(rc_03['coluna'] == 'TOTAL (ÚLTIMOS 12 MESES)')&(rc_03['exercicio'] == 2024)]['valor_bilhoes'].sum()
print(total_rc_01)
print(total_rc_03)
total_rc = total_rc_01 + total_rc_03
print(total_rc)

3.46
17.04
20.5

In [ ]:
#Receitas correntes

receitas_correntes_anexo_01 = [
    'CONTRIBUIÇÕES',
 'RECEITA PATRIMONIAL',
 'RECEITA DE SERVIÇOS',
 'OUTRAS RECEITAS CORRENTES',
 'RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)'
]

receitas_correntes_anexo_03 = [
    'Transferências Correntes',
    'Impostos, Taxas e Contribuições de Melhoria',
]


#'OPERAÇÕES DE CRÉDITO',
#'ALIENAÇÃO DE BENS',
#'TRANSFERÊNCIAS DE CAPITAL',
#'OUTRAS RECEITAS DE CAPITAL',
#'Transferências Constitucionais e Legais',
#'Dedução de Receita para Formação do FUNDEB'





receitas_correntes = pd.concat([df_01, df_03], ignore_index=True)

receitas_correntes['valor_bilhoes'] = (receitas_correntes['valor'] / 1000000000).round(2)

receitas_correntes.pivot_table(index='conta', columns='anexo', values='valor_bilhoes', aggfunc='sum')

anexo                                RREO-Anexo 01
conta
CONTRIBUIÇÕES                                 3.54
OUTRAS RECEITAS CORRENTES                     2.40
RECEITA DE SERVIÇOS                           1.62
RECEITA PATRIMONIAL                           2.29
RECEITAS (INTRA-ORÇAMENTÁRIAS) (II)           5.24

In [64]:
df_03

Empty DataFrame
Columns: [exercicio, demonstrativo, periodo, periodicidade, instituicao, cod_ibge, uf, populacao, anexo, esfera, rotulo, coluna, cod_conta, conta, valor, valor_bilhoes]
Index: []