In [1]:
import requests, json
import pandas as pd

In [11]:
def RREO(an_exercicio, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente):
    url = f'https://apidatalake.tesouro.gov.br/ords/siconfi/tt//rreo?an_exercicio={an_exercicio}&nr_periodo={nr_periodo}&co_tipo_demonstrativo={co_tipo_demonstrativo}&no_anexo={no_anexo}&co_esfera=&id_ente={id_ente}'
    response = requests.get(url)
    if(response.status_code != 200): 
            return({result:'Falhou'})
    dados = response.json()
    return dados

def RGF(an_exercicio,in_periodicidade, nr_periodo, co_tipo_demonstrativo, no_anexo, co_poder, id_ente):
    url = f"https://apidatalake.tesouro.gov.br/ords/siconfi/tt//rgf?an_exercicio={an_exercicio}&in_periodicidade={in_periodicidade}&nr_periodo={nr_periodo}&co_tipo_demonstrativo={co_tipo_demonstrativo}&no_anexo={no_anexo}&co_esfera=&co_poder={co_poder}&id_ente={id_ente}"
    response = requests.get(url)
    if(response.status_code != 200): 
        return({result:'Falhou'})
    dados = response.json()
    return dados

In [16]:
an_exercicio = ['2020','2021','2022','2024']
id_ente = "11" #Código IBGE do Ente.
co_poder = "E" #E = Executivo, L = Legislativo, J = Judiciário, M = Ministério Público, D = Defensoria Pública



rreo_df_01 = pd.DataFrame()
co_tipo_demonstrativo = 'RREO' #tipo de demonstrativo RREO - Bimestre
nr_periodo = '6' #periodo RREO - Bimestre
no_anexo = 'RREO-Anexo+01'

for i in an_exercicio:
    dados = RREO(i, nr_periodo, co_tipo_demonstrativo, no_anexo, id_ente)
    df = dados['items']
    df = pd.DataFrame(df)
    rreo_df_01 = pd.concat([rreo_df_01, df], ignore_index=True)
    rreo_df_01['valor_bilhoes'] = (rreo_df_01['valor'] / 1000000000).round(2)

rgf_df = pd.DataFrame()
co_tipo_demonstrativo = 'RGF' #tipo de demonstrativo RGF - Quadrimestre
nr_periodo = '3' #periodo RGF - Quadrimestre
in_periodicidade = 'Q' #periodicidade RGF - Quadrimestre
no_anexo = 'RGF-Anexo 01' #'RGF-Anexo 02', 'RGF-Anexo 06', 'RGF-Anexo 05', 'RGF-Anexo 04', 'RGF-Anexo 01', 'RGF-Anexo 03'


for j in an_exercicio:
    dados = RGF(j, in_periodicidade, nr_periodo, co_tipo_demonstrativo, no_anexo, co_poder, id_ente)
    df = dados['items']
    df = pd.DataFrame(df)
    rgf_df = pd.concat([rgf_df, df], ignore_index=True)
    rgf_df['valor_bilhoes'] = (rgf_df['valor'] / 1000000000).round(2)

In [17]:
rreo_df_01.head(5)

,exercicio,demonstrativo,periodo,periodicidade,instituicao,cod_ibge,uf,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor,valor_bilhoes
0,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,PREVISÃO INICIAL,ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),8.238173e+09,8.24
1,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,PREVISÃO ATUALIZADA (a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),9.213927e+09,9.21
2,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,No Bimestre (b),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.811558e+09,1.81
3,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,% (b/a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.966000e+01,0.00
4,2020,RREO,6,B,Governo do Estado de Rondônia,11,RO,1777225,RREO-Anexo 01,E,Padrão,Até o Bimestre (c),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),9.153014e+09,9.15

In [19]:
rgf_df.tail(5)

,exercicio,periodo,periodicidade,instituicao,cod_ibge,uf,co_poder,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor,valor_bilhoes
828,2024,3,Q,Governo do Estado de Rondônia,11,RO,E,1616379,RGF-Anexo 01,E,Padrão,% sobre a RCL Ajustada,LimiteMaximoDespesaComPessoalTotal,"LIMITE MÁXIMO (VII) (incisos I, II e III, art....",4.900000e+01,0.00
829,2024,3,Q,Governo do Estado de Rondônia,11,RO,E,1616379,RGF-Anexo 01,E,Padrão,Valor,LimitePrudencialDespesaComPessoalTotal,"LIMITE PRUDENCIAL (VIII) = (0,95 x VII) (parág...",6.605601e+09,6.61
830,2024,3,Q,Governo do Estado de Rondônia,11,RO,E,1616379,RGF-Anexo 01,E,Padrão,% sobre a RCL Ajustada,LimitePrudencialDespesaComPessoalTotal,"LIMITE PRUDENCIAL (VIII) = (0,95 x VII) (parág...",4.655000e+01,0.00
831,2024,3,Q,Governo do Estado de Rondônia,11,RO,E,1616379,RGF-Anexo 01,E,Padrão,Valor,LimiteDeAlertaDespesaComPessoalTotal,"LIMITE DE ALERTA (IX) = (0,90 x VII) (inciso I...",6.257937e+09,6.26
832,2024,3,Q,Governo do Estado de Rondônia,11,RO,E,1616379,RGF-Anexo 01,E,Padrão,% sobre a RCL Ajustada,LimiteDeAlertaDespesaComPessoalTotal,"LIMITE DE ALERTA (IX) = (0,90 x VII) (inciso I...",4.410000e+01,0.00